/**
 * Stage 04 — Event Config: Tickets / Speakers / Sessions / Session-Speakers / Form Fields
 *
 * For each event in data/events.json, upserts in FK-safe order:
 *   ticket_types → speakers → sessions → session_speakers → form_fields
 *
 * Speaker upsert: confirmation_token is auto-generated by the DB default on INSERT
 * and is intentionally excluded from the DO UPDATE SET clause. Not including it
 * in the upsert object means PostgREST's ON CONFLICT DO UPDATE will not touch it,
 * preserving any token already issued.
 *
 * Session speakers: built from each session's speaker_ids array as (session_id, speaker_id)
 * pairs, upserted ON CONFLICT (session_id, speaker_id).
 *
 * No INSERT triggers on any of these tables.
 */

import type { SupabaseClient } from '@supabase/supabase-js'
import type { EventsFileData, EventDef } from '../lib/event-types'
import { log } from '../lib/logger'
import type { StageSummary } from '../lib/logger'

interface EventCounts {
  tickets: number
  speakers: number
  sessions: number
  sessionSpeakers: number
  formFields: number
}

function planCounts(event: EventDef): EventCounts {
  const sessionSpeakers = (event.sessions ?? []).reduce(
    (s, sn) => s + (sn.speaker_ids?.length ?? 0),
    0,
  )
  return {
    tickets:        event.ticket_types?.length ?? 0,
    speakers:       event.speakers?.length     ?? 0,
    sessions:       event.sessions?.length     ?? 0,
    sessionSpeakers,
    formFields:     event.form_fields?.length  ?? 0,
  }
}

async function upsertTicketTypes(supabase: SupabaseClient, event: EventDef): Promise<number> {
  const items = event.ticket_types ?? []
  if (!items.length) return 0
  const { error } = await supabase.from('ticket_types').upsert(
    items.map((t, i) => ({
      id:              t.id,
      event_id:        event.id,
      name:            t.name,
      type:            t.type,
      price_cents:     t.price_cents    ?? 0,
      delivery_method: t.delivery_method ?? 'in_person',
      is_active:       t.is_active      ?? true,
      sort_order:      t.sort_order     ?? i,
    })),
    { onConflict: 'id' },
  )
  if (error) throw new Error(`upsert ticket_types for "${event.title}": ${error.message}`)
  return items.length
}

async function upsertSpeakers(supabase: SupabaseClient, event: EventDef): Promise<number> {
  const items = event.speakers ?? []
  if (!items.length) return 0
  // confirmation_token deliberately excluded — DB default generates it on INSERT,
  // and omitting it from the upsert object means it is NOT in the DO UPDATE SET clause.
  const { error } = await supabase.from('speakers').upsert(
    items.map((s, i) => ({
      id:           s.id,
      event_id:     event.id,
      name:         s.name,
      bio:          s.bio          ?? null,
      job_title:    s.job_title    ?? null,
      company:      s.company      ?? null,
      photo_url:    s.photo_url    ?? null,
      status:       s.status       ?? 'invited',
      event_role:   s.event_role   ?? 'speaker',
      confirmed_at: s.confirmed_at ?? null,
      sort_order:   s.sort_order   ?? i,
    })),
    { onConflict: 'id' },
  )
  if (error) throw new Error(`upsert speakers for "${event.title}": ${error.message}`)
  return items.length
}

async function upsertSessions(supabase: SupabaseClient, event: EventDef): Promise<number> {
  const items = event.sessions ?? []
  if (!items.length) return 0
  const { error } = await supabase.from('sessions').upsert(
    items.map((sn, i) => ({
      id:               sn.id,
      event_id:         event.id,
      title:            sn.title,
      description:      sn.description    ?? null,
      session_type:     sn.session_type   ?? 'talk',
      track_id:         sn.track_id       ?? null,
      room_id:          sn.room_id        ?? null,
      starts_at:        sn.starts_at,
      ends_at:          sn.ends_at,
      ce_credit_hours:  sn.ce_credit_hours ?? 0,
      is_published:     sn.is_published    ?? true,
      video_url:        sn.video_url       ?? null,
      sort_order:       sn.sort_order      ?? i,
    })),
    { onConflict: 'id' },
  )
  if (error) throw new Error(`upsert sessions for "${event.title}": ${error.message}`)
  return items.length
}

async function upsertSessionSpeakers(supabase: SupabaseClient, event: EventDef): Promise<number> {
  const rows: Array<{ session_id: string; speaker_id: string; sort_order: number }> = []
  for (const sn of event.sessions ?? []) {
    const speakerIds = sn.speaker_ids ?? []
    speakerIds.forEach((spId, idx) => {
      rows.push({ session_id: sn.id, speaker_id: spId, sort_order: idx })
    })
  }
  if (!rows.length) return 0
  const { error } = await supabase.from('session_speakers').upsert(rows, {
    onConflict: 'session_id,speaker_id',
  })
  if (error) throw new Error(`upsert session_speakers for "${event.title}": ${error.message}`)
  return rows.length
}

async function upsertFormFields(supabase: SupabaseClient, event: EventDef): Promise<number> {
  const items = event.form_fields ?? []
  if (!items.length) return 0
  const { error } = await supabase.from('form_fields').upsert(
    items.map((f, i) => ({
      id:          f.id,
      event_id:    event.id,
      field_key:   f.field_key,
      label:       f.label,
      field_type:  f.field_type,
      is_required: f.is_required ?? false,
      sort_order:  f.sort_order  ?? i,
      options:     f.options     ?? null,
    })),
    { onConflict: 'id' },
  )
  if (error) throw new Error(`upsert form_fields for "${event.title}": ${error.message}`)
  return items.length
}

export async function runEventConfig(
  supabase: SupabaseClient,
  data: EventsFileData,
  opts: { dryRun: boolean },
): Promise<StageSummary> {
  log.section('Stage 04: Event Config (tickets / speakers / sessions / form fields)')

  // Planned totals
  let planTickets = 0; let planSpeakers = 0; let planSessions = 0
  let planSS = 0;      let planFF = 0
  for (const event of data.events) {
    const c = planCounts(event)
    planTickets += c.tickets; planSpeakers += c.speakers; planSessions += c.sessions
    planSS += c.sessionSpeakers; planFF += c.formFields
  }
  const totalPlanned = planTickets + planSpeakers + planSessions + planSS + planFF
  log.info(
    `Plan: ${planTickets} tickets, ${planSpeakers} speakers, ${planSessions} sessions, ` +
    `${planSS} session_speakers, ${planFF} form_fields`,
  )

  if (opts.dryRun) {
    for (const event of data.events) {
      const c = planCounts(event)
      log.dry(
        `event "${event.title}"\n` +
        `         tickets: ${c.tickets}, speakers: ${c.speakers}, sessions: ${c.sessions}, ` +
        `session_speakers: ${c.sessionSpeakers}, form_fields: ${c.formFields}`,
      )
    }
    log.info('')
    log.ok('Dry-run complete — no writes made')
    return { stage: 'event-config', planned: totalPlanned, actual: 0, note: 'dry-run' }
  }

  let actTickets = 0; let actSpeakers = 0; let actSessions = 0
  let actSS = 0;      let actFF = 0

  for (const event of data.events) {
    console.log(`\n  \x1b[1m▸ ${event.title}\x1b[0m`)

    actTickets  += await upsertTicketTypes(supabase, event)
    actSpeakers += await upsertSpeakers(supabase, event)
    actSessions += await upsertSessions(supabase, event)
    actSS       += await upsertSessionSpeakers(supabase, event)
    actFF       += await upsertFormFields(supabase, event)

    const c = planCounts(event)
    log.ok(
      `tickets: ${c.tickets}, speakers: ${c.speakers}, sessions: ${c.sessions}, ` +
      `session_speakers: ${c.sessionSpeakers}, form_fields: ${c.formFields}`,
    )
  }

  const actual = actTickets + actSpeakers + actSessions + actSS + actFF
  log.ok(
    `Stage 04 complete — ${actTickets} tickets, ${actSpeakers} speakers, ` +
    `${actSessions} sessions, ${actSS} session_speakers, ${actFF} form_fields`,
  )
  return { stage: 'event-config', planned: totalPlanned, actual }
}
