/**
 * Stage 05 — Registrations
 *
 * Generates registration rows deterministically using a per-event LCG seeded
 * from djb2Hash(event_slug).  Order per event: heroes → fixtures → guests
 * (confirmed, cancelled, refunded, pending, waitlisted).
 *
 * TRIGGER NOTE:
 *   trg_registration_count (AFTER INSERT OR UPDATE) auto-increments
 *   events.registration_count and ticket_types.quantity_sold when status='confirmed'.
 *   DO NOT set those counters manually.
 *
 *   qr_code and certificate_token are auto-generated by DB defaults — NEVER
 *   included in insert payloads (unique constraint on both).
 *
 * Batch limit: ≤200 rows per supabase .insert() call.
 */

import type { SupabaseClient } from '@supabase/supabase-js'
import type { EventsFileData, EventDef, TicketTypeDef, FormFieldDef } from '../lib/event-types'
import { log } from '../lib/logger'
import type { StageSummary } from '../lib/logger'

// ─── Public types (re-exported for run.ts) ────────────────────────────────────

export interface DiscountCodeDef {
  id: string
  event_slug: string
  code: string
  discount_type: 'percent' | 'fixed'
  discount_value: number
  max_uses?: number
  uses_count?: number
  valid_until?: string
  is_active?: boolean
}

export interface FieldResponseRates {
  dietary_restrictions_rate?: number
  tshirt_size_rate?: number
  company_name_rate?: number
  experience_level_rate?: number
}

export interface EventRegDef {
  slug: string
  confirmed?: number
  pending?: number
  cancelled?: number
  waitlisted?: number
  refunded?: number
  delivery_method?: 'in_person' | 'virtual'
  delivery_split?: Record<string, number>
  ticket_split: Record<string, number>
  hero_emails: string[]
  fixture_indices: number[]
  sms_opt_in_rate?: number
  discounted_ticket?: string
  discounted_count?: number
  discount_code_id?: string
  discount_amount_cents?: number
  ce_field_responses?: boolean
  member_id_rate?: number
  field_responses?: FieldResponseRates
}

export interface RegistrationsFileData {
  discount_codes: DiscountCodeDef[]
  events: EventRegDef[]
}

// ─── LCG seeded RNG ───────────────────────────────────────────────────────────

function djb2Hash(s: string): number {
  let h = 5381
  for (let i = 0; i < s.length; i++) h = (((h << 5) + h) + s.charCodeAt(i)) & 0xffffffff
  return h >>> 0
}

class Lcg {
  private s: number
  constructor(seed: number) { this.s = seed >>> 0 }
  next(): number {
    this.s = (Math.imul(1664525, this.s) + 1013904223) >>> 0
    return this.s
  }
  float(): number { return this.next() / 0x100000000 }
  int(max: number): number { return max <= 0 ? 0 : this.next() % max }
}

// ─── Name / domain arrays (exactly 60 + 60 + 10) ─────────────────────────────

const FIRST_NAMES = [
  'James', 'Maria', 'John', 'Patricia', 'Robert', 'Jennifer', 'Michael', 'Linda',
  'William', 'Barbara', 'David', 'Elizabeth', 'Richard', 'Susan', 'Joseph', 'Jessica',
  'Thomas', 'Sarah', 'Charles', 'Karen', 'Christopher', 'Lisa', 'Daniel', 'Nancy',
  'Matthew', 'Betty', 'Anthony', 'Margaret', 'Mark', 'Sandra', 'Donald', 'Ashley',
  'Steven', 'Dorothy', 'Paul', 'Kimberly', 'Andrew', 'Emily', 'Kenneth', 'Donna',
  'George', 'Michelle', 'Joshua', 'Carol', 'Kevin', 'Amanda', 'Brian', 'Melissa',
  'Edward', 'Deborah', 'Ronald', 'Stephanie', 'Timothy', 'Rebecca', 'Jason', 'Sharon',
  'Jeffrey', 'Laura', 'Ryan', 'Cynthia',
]

const LAST_NAMES = [
  'Smith', 'Johnson', 'Williams', 'Brown', 'Jones', 'Garcia', 'Miller', 'Davis',
  'Rodriguez', 'Martinez', 'Hernandez', 'Lopez', 'Gonzalez', 'Wilson', 'Anderson', 'Thomas',
  'Taylor', 'Moore', 'Jackson', 'Martin', 'Lee', 'Perez', 'Thompson', 'White',
  'Harris', 'Sanchez', 'Clark', 'Ramirez', 'Lewis', 'Robinson', 'Walker', 'Young',
  'Allen', 'King', 'Wright', 'Scott', 'Torres', 'Nguyen', 'Hill', 'Flores',
  'Green', 'Adams', 'Nelson', 'Baker', 'Hall', 'Rivera', 'Campbell', 'Mitchell',
  'Carter', 'Roberts', 'Gomez', 'Phillips', 'Evans', 'Turner', 'Diaz', 'Parker',
  'Cruz', 'Edwards', 'Collins', 'Reyes',
]

const DOMAINS = [
  'gmail.com', 'yahoo.com', 'outlook.com', 'hotmail.com', 'icloud.com',
  'aol.com', 'protonmail.com', 'mail.com', 'live.com', 'msn.com',
]

const COMPANIES = [
  'Summit Solutions', 'Metro Tech Group', 'Blueprint Creative', 'Harbor Ridge Consulting',
  'Cornerstone Digital', 'Pinnacle Marketing', 'Lakeside Ventures', 'Apex Group',
  'Heritage Financial', 'Mosaic Media', 'Northbridge Associates', 'Clearview Staffing',
  'Riverstone Capital', 'Ironwood Development', 'Brightside Agency', 'Summit Street Bakery',
  'Delta Consulting Group', 'Oakwood Industries', 'Coastal Design Studio', 'TechBridge Solutions',
]

// ─── UUID helpers ─────────────────────────────────────────────────────────────

function makeRegId(eventIdx: number, seq: number): string {
  // Format: 08{EEEEEE}-{seq_lo_4hex}-4001-8001-{seq_12hex}
  const e6 = eventIdx.toString(16).padStart(6, '0')
  const s12 = seq.toString(16).padStart(12, '0')
  const sLo = s12.slice(-4)
  return `08${e6}-${sLo}-4001-8001-${s12}`
}

function makeFieldResponseId(eventIdx: number, regSeq: number, fieldSlot: number): string {
  // Format: 09{EEEEEE}-{seq_lo_4hex}-{fieldSlot_4hex}-8001-{seq_12hex}
  const e6 = eventIdx.toString(16).padStart(6, '0')
  const s12 = regSeq.toString(16).padStart(12, '0')
  const sLo = regSeq.toString(16).padStart(4, '0')
  const f4 = fieldSlot.toString(16).padStart(4, '0')
  return `09${e6}-${sLo}-${f4}-8001-${s12}`
}

// ─── Weight selection ─────────────────────────────────────────────────────────

function selectByWeight(split: Record<string, number>, rand: number): string {
  let cumul = 0
  for (const [name, weight] of Object.entries(split)) {
    cumul += weight
    if (rand < cumul) return name
  }
  return Object.keys(split).at(-1)!
}

// ─── Planned count helper (dry-run, no DB) ────────────────────────────────────

function planCounts(er: EventRegDef): { regs: number; fieldResponses: number } {
  const confirmed = er.confirmed ?? 0
  const total = confirmed + (er.cancelled ?? 0) + (er.refunded ?? 0) +
                (er.pending ?? 0) + (er.waitlisted ?? 0)
  let fr = 0
  if (er.ce_field_responses) {
    fr = confirmed + Math.floor(confirmed * (er.member_id_rate ?? 0))
  } else if (er.field_responses) {
    const f = er.field_responses
    // BSBW: same 60% of confirmed gets all three fields → rate × confirmed × num_fields_used
    if (f.dietary_restrictions_rate !== undefined) fr += Math.floor(confirmed * f.dietary_restrictions_rate)
    if (f.tshirt_size_rate !== undefined)          fr += Math.floor(confirmed * f.tshirt_size_rate)
    if (f.company_name_rate !== undefined)          fr += Math.floor(confirmed * f.company_name_rate)
    if (f.experience_level_rate !== undefined)      fr += Math.floor(confirmed * f.experience_level_rate)
  }
  return { regs: total, fieldResponses: fr }
}

// ─── Batch insert helper ──────────────────────────────────────────────────────

async function batchInsert<T extends object>(
  supabase: SupabaseClient,
  table: string,
  rows: T[],
  onConflict: string,
): Promise<number> {
  const BATCH = 200
  let count = 0
  for (let i = 0; i < rows.length; i += BATCH) {
    const chunk = rows.slice(i, i + BATCH)
    const { error } = await supabase.from(table).upsert(chunk as Record<string, unknown>[], { onConflict })
    if (error) throw new Error(`upsert ${table} (batch ${Math.floor(i / BATCH) + 1}): ${error.message}`)
    count += chunk.length
  }
  return count
}

// ─── Discount code upsert ─────────────────────────────────────────────────────

async function upsertDiscountCodes(
  supabase: SupabaseClient,
  codes: DiscountCodeDef[],
  eventMap: Map<string, EventDef>,
): Promise<number> {
  if (!codes.length) return 0
  const rows = codes.map(c => {
    const event = eventMap.get(c.event_slug)
    if (!event) throw new Error(`discount_code "${c.code}": unknown event_slug "${c.event_slug}"`)
    return {
      id:             c.id,
      event_id:       event.id,
      code:           c.code,
      discount_type:  c.discount_type,
      discount_value: c.discount_value,
      max_uses:       c.max_uses   ?? null,
      uses_count:     c.uses_count ?? 0,
      valid_until:    c.valid_until ?? null,
      is_active:      c.is_active  ?? true,
    }
  })
  const { error } = await supabase.from('discount_codes').upsert(rows, { onConflict: 'id' })
  if (error) throw new Error(`upsert discount_codes: ${error.message}`)
  return rows.length
}

// ─── Profile resolution ───────────────────────────────────────────────────────

interface ProfileRow { id: string; email: string; full_name: string | null }

async function resolveHeroes(
  supabase: SupabaseClient,
  emails: string[],
): Promise<Map<string, ProfileRow>> {
  const out = new Map<string, ProfileRow>()
  if (!emails.length) return out
  const { data, error } = await supabase
    .from('profiles')
    .select('id, email, full_name')
    .in('email', emails)
  if (error) throw new Error(`profiles lookup for heroes: ${error.message}`)
  for (const p of data ?? []) out.set(p.email as string, p as ProfileRow)
  return out
}

async function resolveFixtures(supabase: SupabaseClient): Promise<ProfileRow[]> {
  const { data, error } = await supabase
    .from('profiles')
    .select('id, email, full_name')
    .like('email', '%+fixture%')
    .order('email')
  if (error) throw new Error(`profiles lookup for fixtures: ${error.message}`)
  return (data ?? []) as ProfileRow[]
}

// ─── Registration row builder ─────────────────────────────────────────────────

interface RegRow {
  id: string
  event_id: string
  ticket_type_id: string
  user_id: string | null
  attendee_email: string
  attendee_name: string
  attendee_phone: string | null
  status: string
  payment_method: string
  delivery_method: string
  amount_paid_cents: number
  discount_code_id: string | null
  discount_amount_cents: number
  refund_amount_cents: number
  refunded_at: string | null
  confirmation_sent_at: string | null
  waitlist_position: number | null
  sms_opt_in: boolean
  sms_opt_in_at: string | null
  created_at: string
}

interface FieldResponseRow {
  id: string
  registration_id: string
  field_id: string
  value: string
}

function buildEventRows(
  er: EventRegDef,
  eventDef: EventDef,
  eventIdx: number,
  heroes: Map<string, ProfileRow>,
  fixtures: ProfileRow[],
): { regs: RegRow[]; fieldResponses: FieldResponseRow[] } {
  const rng = new Lcg(djb2Hash(er.slug))
  const nowMs = Date.now()
  const startMs = new Date(eventDef.start_at).getTime()

  // Ticket type id map (by name)
  const ticketMap = new Map<string, TicketTypeDef>()
  for (const t of eventDef.ticket_types ?? []) ticketMap.set(t.name, t)

  // Form field id map (by field_key)
  const fieldMap = new Map<string, FormFieldDef>()
  for (const f of eventDef.form_fields ?? []) fieldMap.set(f.field_key, f)

  // Event status helpers
  const status = eventDef.status
  const isEndedOrArchived = status === 'ended' || status === 'archived'

  function backdatedCreatedAt(): string {
    const minDays = isEndedOrArchived ? 7 : 7
    const maxDays = isEndedOrArchived ? 120 : 90
    const base = isEndedOrArchived ? startMs : Math.min(nowMs, startMs)
    const days = minDays + rng.int(maxDays - minDays + 1)
    return new Date(base - days * 86400000).toISOString()
  }

  function confirmationSentAt(createdAt: string): string {
    if (isEndedOrArchived) {
      return new Date(startMs - 7 * 86400000).toISOString()
    }
    // live/published: 0-48 hours after created_at
    const created = new Date(createdAt).getTime()
    return new Date(created + rng.int(48 * 3600000)).toISOString()
  }

  function ticketFor(ticketName: string): TicketTypeDef {
    const t = ticketMap.get(ticketName)
    if (!t) throw new Error(`ticket "${ticketName}" not found in event "${eventDef.slug}"`)
    return t
  }

  function resolveDelivery(): 'in_person' | 'virtual' {
    if (er.delivery_method) return er.delivery_method
    if (er.delivery_split) {
      return selectByWeight(er.delivery_split, rng.float()) as 'in_person' | 'virtual'
    }
    return 'in_person'
  }

  function amountPaid(t: TicketTypeDef, hasDiscount: boolean): number {
    const price = t.price_cents ?? 0
    if (!hasDiscount) return price
    const dc = er.discount_amount_cents
    if (dc !== undefined) return Math.max(0, price - dc)
    // percent discount
    const pct = er.discounted_ticket === t.name ? (15 / 100) : 0  // default 15% for EARLYBIRD15
    return Math.round(price * (1 - pct))
  }

  function discountAmountCents(t: TicketTypeDef, hasDiscount: boolean): number {
    if (!hasDiscount) return 0
    const price = t.price_cents ?? 0
    const dc = er.discount_amount_cents
    if (dc !== undefined) return Math.min(dc, price)
    return price - amountPaid(t, true)
  }

  const confirmed = er.confirmed ?? 0
  const cancelled = er.cancelled ?? 0
  const refunded  = er.refunded  ?? 0
  const pending   = er.pending   ?? 0
  const waitlisted = er.waitlisted ?? 0
  const heroCount = er.hero_emails.length
  const fixtureCount = er.fixture_indices.length

  const confirmedGuests = Math.max(0, confirmed - heroCount - fixtureCount)
  const guestTotal = confirmedGuests + cancelled + refunded + pending + waitlisted

  const regs: RegRow[] = []
  let seq = 0
  let discountedSoFar = 0
  const discountMax = er.discounted_count ?? 0
  let waitlistPos = 0

  // ── SMS phone counter (per-event, 0-indexed) ──────────────────────────────
  let smsCounter = 0
  const smsRate = er.sms_opt_in_rate ?? 0

  function smsPhone(): string {
    const n = smsCounter++
    return `(555) 555-${String(n + 100).padStart(4, '0')}`
  }

  // ── Helper: build one registration row ────────────────────────────────────
  function makeRow(
    userId: string | null,
    email: string,
    name: string,
    ticketName: string,
    rowStatus: string,
  ): RegRow {
    seq++
    const id = makeRegId(eventIdx, seq)
    const t = ticketFor(ticketName)
    const delivery = resolveDelivery()
    const createdAt = backdatedCreatedAt()

    const isDiscountable = er.discounted_ticket === ticketName && discountedSoFar < discountMax
    const hasDiscount = isDiscountable && (rowStatus === 'confirmed' || rowStatus === 'refunded' || rowStatus === 'cancelled')
    if (isDiscountable) discountedSoFar++

    const paid = (rowStatus === 'confirmed' || rowStatus === 'refunded')
      ? amountPaid(t, hasDiscount)
      : 0

    const confSentAt = (rowStatus === 'confirmed' || rowStatus === 'refunded')
      ? confirmationSentAt(createdAt)
      : null

    const refundedAt = rowStatus === 'refunded'
      ? new Date(new Date(confSentAt!).getTime() + 2 * 86400000).toISOString()
      : null

    const wp = rowStatus === 'waitlisted' ? ++waitlistPos : null

    const smsRand = rng.float()
    const doSms = smsRate > 0 && smsRand < smsRate
    const phone = doSms ? smsPhone() : null
    const smsAt = doSms ? (confSentAt ?? createdAt) : null

    return {
      id, event_id: eventDef.id, ticket_type_id: t.id, user_id: userId,
      attendee_email: email, attendee_name: name, attendee_phone: phone,
      status: rowStatus, payment_method: 'stripe', delivery_method: delivery,
      amount_paid_cents: paid,
      discount_code_id: hasDiscount ? (er.discount_code_id ?? null) : null,
      discount_amount_cents: hasDiscount ? discountAmountCents(t, true) : 0,
      refund_amount_cents: rowStatus === 'refunded' ? paid : 0,
      refunded_at: refundedAt,
      confirmation_sent_at: confSentAt,
      waitlist_position: wp,
      sms_opt_in: doSms, sms_opt_in_at: smsAt,
      created_at: createdAt,
    }
  }

  // ── Heroes ────────────────────────────────────────────────────────────────
  const ticketNames = Object.keys(er.ticket_split)
  for (const email of er.hero_emails) {
    const profile = heroes.get(email)
    const name = profile?.full_name ?? email.split('@')[0]
    const ticketName = ticketNames[0]  // heroes use the first ticket in the split
    regs.push(makeRow(profile?.id ?? null, email, name, ticketName, 'confirmed'))
  }

  // ── Fixtures ──────────────────────────────────────────────────────────────
  for (const idx of er.fixture_indices) {
    const profile = fixtures[idx]
    if (!profile) {
      log.warn(`fixture index ${idx} not found — skipping`)
      continue
    }
    const ticketName = selectByWeight(er.ticket_split, rng.float())
    regs.push(makeRow(profile.id, profile.email, profile.full_name ?? `Fixture ${idx}`, ticketName, 'confirmed'))
  }

  // ── Guests (confirmed → cancelled → refunded → pending → waitlisted) ──────
  const guestStatuses: Array<[string, number]> = [
    ['confirmed', confirmedGuests],
    ['cancelled', cancelled],
    ['refunded',  refunded],
    ['pending',   pending],
    ['waitlisted', waitlisted],
  ]

  let guestSeq = 0
  for (const [gStatus, count] of guestStatuses) {
    for (let i = 0; i < count; i++) {
      guestSeq++
      const fi = rng.int(60)
      const li = rng.int(60)
      const firstName = FIRST_NAMES[fi]
      const lastName  = LAST_NAMES[li]
      const domain    = DOMAINS[rng.int(10)]
      const name      = `${firstName} ${lastName}`
      const email     = `${firstName.toLowerCase()}.${lastName.toLowerCase()}.${guestSeq}@${domain}`
      const ticketName = selectByWeight(er.ticket_split, rng.float())
      regs.push(makeRow(null, email, name, ticketName, gStatus))
    }
  }

  // ── Field responses ───────────────────────────────────────────────────────
  const fieldResponses: FieldResponseRow[] = []

  // Collect confirmed reg IDs in insertion order (hero + fixture + confirmed guests)
  const confirmedRegs = regs.filter(r => r.status === 'confirmed')

  function pushFR(regId: string, regSeqNum: number, fieldKey: string, value: string, slot: number) {
    const field = fieldMap.get(fieldKey)
    if (!field) return
    fieldResponses.push({
      id: makeFieldResponseId(eventIdx, regSeqNum, slot),
      registration_id: regId,
      field_id: field.id,
      value,
    })
  }

  if (er.ce_field_responses) {
    // SAUP: ALL confirmed get ce_eligibility; member_id_rate% also get member_id
    const memberIdRate = er.member_id_rate ?? 0
    let frIdx = 0
    for (const reg of confirmedRegs) {
      const regSeqNum = parseInt(reg.id.split('-').at(-1)!, 16)
      pushFR(reg.id, regSeqNum, 'ce_eligibility', 'true', 0)
      if (rng.float() < memberIdRate) {
        const memberId = 'AICP-' + rng.int(999999).toString().padStart(6, '0')
        pushFR(reg.id, regSeqNum, 'member_id', memberId, 1)
      }
      frIdx++
    }
  } else if (er.field_responses) {
    const f = er.field_responses
    const dietaryOptions = ['No restrictions', 'Vegetarian', 'Vegan', 'Gluten-Free', 'Kosher', 'Halal']
    const tshirtOptions  = ['XS', 'S', 'M', 'L', 'XL', 'XXL']
    const expOptions     = ['Beginner', 'Intermediate', 'Advanced', 'Staff+']
    let cycleIdx = 0

    for (const reg of confirmedRegs) {
      const regSeqNum = parseInt(reg.id.split('-').at(-1)!, 16)

      if (f.dietary_restrictions_rate !== undefined && rng.float() < f.dietary_restrictions_rate) {
        const value = dietaryOptions[cycleIdx % dietaryOptions.length]
        pushFR(reg.id, regSeqNum, 'dietary_restrictions', value, 0)
      }
      if (f.tshirt_size_rate !== undefined && rng.float() < f.tshirt_size_rate) {
        const value = tshirtOptions[cycleIdx % tshirtOptions.length]
        pushFR(reg.id, regSeqNum, 'tshirt_size', value, 1)
      }
      if (f.company_name_rate !== undefined && rng.float() < f.company_name_rate) {
        const value = COMPANIES[rng.int(COMPANIES.length)]
        pushFR(reg.id, regSeqNum, 'company_name', value, 2)
      }
      if (f.experience_level_rate !== undefined && rng.float() < f.experience_level_rate) {
        const value = expOptions[rng.int(expOptions.length)]
        pushFR(reg.id, regSeqNum, 'experience_level', value, 3)
      }
      cycleIdx++
    }
  }

  return { regs, fieldResponses }
}

// ─── Main exported function ───────────────────────────────────────────────────

export async function runRegistrations(
  supabase: SupabaseClient,
  regData: RegistrationsFileData,
  eventsData: EventsFileData,
  opts: { dryRun: boolean },
): Promise<StageSummary> {
  log.section('Stage 05: Registrations (seeded RNG, ~1215 rows)')

  // Build lookup maps
  const eventMap = new Map(eventsData.events.map(e => [e.slug, e]))
  const eventIdxMap = new Map(eventsData.events.map((e, i) => [e.slug, i + 1]))

  // ── Planned counts ─────────────────────────────────────────────────────────
  let totalPlannedRegs = 0
  let totalPlannedFR   = 0
  for (const er of regData.events) {
    const c = planCounts(er)
    totalPlannedRegs += c.regs
    totalPlannedFR   += c.fieldResponses
  }
  const dcCount = regData.discount_codes.length
  const totalPlanned = totalPlannedRegs + totalPlannedFR + dcCount

  log.info(
    `Plan: ${dcCount} discount_codes, ${totalPlannedRegs} registrations, ` +
    `${totalPlannedFR} field_responses (total ${totalPlanned})`
  )

  // ── Dry-run: log per-event breakdown and exit ──────────────────────────────
  if (opts.dryRun) {
    for (const er of regData.events) {
      const c = planCounts(er)
      const parts: string[] = []
      if (er.confirmed)  parts.push(`confirmed=${er.confirmed}`)
      if (er.cancelled)  parts.push(`cancelled=${er.cancelled}`)
      if (er.refunded)   parts.push(`refunded=${er.refunded}`)
      if (er.pending)    parts.push(`pending=${er.pending}`)
      if (er.waitlisted) parts.push(`waitlisted=${er.waitlisted}`)
      log.dry(
        `event "${er.slug}": ${c.regs} regs (${parts.join(', ')}) + ${c.fieldResponses} field_responses`
      )
    }
    log.info('')
    log.ok('Dry-run complete — no writes made')
    return { stage: 'registrations', planned: totalPlanned, actual: 0, note: 'dry-run' }
  }

  // ── Execute mode ───────────────────────────────────────────────────────────

  // 1. Upsert discount codes
  log.info('Upserting discount codes…')
  const dcActual = await upsertDiscountCodes(supabase, regData.discount_codes, eventMap)
  log.ok(`${dcActual} discount_codes upserted`)

  // 2. Resolve hero and fixture profiles (single query each, re-used across events)
  const allHeroEmails = [...new Set(regData.events.flatMap(er => er.hero_emails))]
  const heroProfiles   = await resolveHeroes(supabase, allHeroEmails)
  const fixtureProfiles = await resolveFixtures(supabase)

  for (const email of allHeroEmails) {
    if (!heroProfiles.has(email)) log.warn(`hero profile not found for ${email} — will register as guest`)
  }

  // 3. Process each event
  let totalActualRegs = 0
  let totalActualFR   = 0

  for (const er of regData.events) {
    const eventDef = eventMap.get(er.slug)
    if (!eventDef) throw new Error(`event "${er.slug}" not found in events.json`)
    const eventIdx = eventIdxMap.get(er.slug)!

    console.log(`\n  \x1b[1m▸ ${er.slug}\x1b[0m`)

    const { regs, fieldResponses } = buildEventRows(er, eventDef, eventIdx, heroProfiles, fixtureProfiles)

    // Batch insert registrations (≤200 per call)
    const regActual = await batchInsert(supabase, 'registrations', regs, 'id')
    totalActualRegs += regActual

    // Batch insert field responses (≤200 per call)
    let frActual = 0
    if (fieldResponses.length > 0) {
      frActual = await batchInsert(supabase, 'registration_field_responses', fieldResponses, 'id')
      totalActualFR += frActual
    }

    const c = planCounts(er)
    log.ok(`${regActual}/${c.regs} regs, ${frActual}/${c.fieldResponses} field_responses`)
  }

  const actual = dcActual + totalActualRegs + totalActualFR
  log.ok(
    `Stage 05 complete — ${dcActual} discount_codes, ` +
    `${totalActualRegs} registrations, ${totalActualFR} field_responses`
  )
  return { stage: 'registrations', planned: totalPlanned, actual }
}
