import type { AnnouncementTemplate } from './types'

export const ANNOUNCEMENT_TEMPLATES: AnnouncementTemplate[] = [
  // ── ORIGINAL 7 ───────────────────────────────────────────────────────────────
  {
    id: 'welcome',
    name: 'Welcome',
    description: 'Sent immediately after registration',
    trigger: 'on_registration',
    channels: ['email', 'push'],
    audience: 'newly_registered',
    subject: 'Welcome to {event_title}!',
    subjects: [
      'Welcome to {event_title}!',
      "You're in — {event_title} registration confirmed",
      "{first_name}, we'll see you at {event_title}",
    ],
    body: "Hi {attendee_name},\n\nYou're registered for {event_title} on {event_date} at {venue_name}. We're excited to see you!\n\nSave your QR code: {qr_url}\nView the agenda: {agenda_url}\nAdd to your calendar: {ics_url}\n\nQuestions? Reply to this email.\n\n— {org_name}",
  },
  {
    id: 'day-of-reminder',
    name: 'Day-of reminder',
    description: 'Sent morning of event',
    trigger: 'scheduled',
    channels: ['email', 'push'],
    audience: 'confirmed',
    subject: 'See you today at {event_title}',
    subjects: [
      'See you today at {event_title}',
      '{event_title} is today — here\'s everything you need',
      'Today is the day — {event_title} starts in {hours_until_start} hours',
    ],
    body: "Hi {attendee_name},\n\nTonight's the night (or today's the day)! {event_title} kicks off at {event_start_time} at {venue_name}.\n\nDon't forget your QR code: {qr_url}\n\nSee you soon!\n\n— {org_name}",
  },
  {
    id: 'schedule-update',
    name: 'Schedule update',
    description: 'Generic schedule change announcement',
    channels: ['email', 'push'],
    audience: 'confirmed',
    subject: 'Schedule update for {event_title}',
    body: 'Quick update — {DESCRIBE_CHANGE_HERE}.\n\nThe updated agenda is here: {agenda_url}\n\nThanks for your flexibility.\n\n— {org_name}',
  },
  {
    id: 'speaker-spotlight',
    name: 'Speaker spotlight',
    description: 'Promote a specific speaker',
    channels: ['email'],
    audience: 'confirmed',
    subject: "Don't miss {speaker_name} at {event_title}",
    body: '{speaker_name} ({speaker_role} at {speaker_company}) is speaking on "{session_title}" at {session_time}.\n\nHere\'s what to expect: {session_description}\n\nView session: {session_url}',
  },
  {
    id: 'thank-you-and-survey',
    name: 'Post-event thank-you + survey',
    description: 'Thank attendees and link to survey',
    trigger: 'post_event',
    channels: ['email'],
    audience: 'confirmed',
    subject: 'Thank you for attending {event_title}',
    subjects: [
      'Thank you for attending {event_title}',
      '{first_name}, tell us how we did — 2 minutes',
      'How was {event_title}? Quick feedback requested',
    ],
    body: 'Hi {attendee_name},\n\nThank you for being part of {event_title}. We hope it was valuable.\n\nWe\'d love your feedback (90 seconds): {survey_url}\n\n{certificate_download_link_if_eligible}\n\nUntil next time,\n— {org_name}',
  },
  {
    id: 'networking-nudge',
    name: 'Networking nudge',
    description: 'Encourage attendees to engage with networking features',
    channels: ['email', 'push'],
    audience: 'confirmed_pre_event',
    subject: 'Try the {event_title} networking feature',
    body: "Hi {attendee_name},\n\nWe've set up a networking directory + meetup scheduler. Get a head start on who you want to meet.\n\nOpt in here: {profile_url}",
  },
  {
    id: 'last-call',
    name: 'Last call',
    description: 'Sent 24-48h before registration closes',
    channels: ['email', 'push'],
    audience: 'public',
    subject: 'Last day to register for {event_title}',
    subjects: [
      'Last day to register for {event_title}',
      'Final hours: {spots_remaining} spots left for {event_title}',
      'This is your last chance to join us at {event_title}',
    ],
    body: 'Registration for {event_title} closes tomorrow.\n\n{capacity_remaining_blurb}\n\nRegister: {event_url}',
  },

  // ── NEW 13 ────────────────────────────────────────────────────────────────────
  {
    id: 'save-the-date',
    name: 'Save the Date',
    description: 'First touchpoint — sent 8-12 weeks before the event',
    channels: ['email'],
    audience: 'subscribers',
    subject: 'Save the Date — {event_title} is coming {event_month_year}',
    subjects: [
      'Save the Date — {event_title} is coming {event_month_year}',
      'Mark your calendar: {event_title} | {event_date_short}',
      '{event_title} is officially happening — {event_date_short}',
    ],
    body: "Hi {first_name},\n\nWe have exciting news. {event_title} is officially on the calendar.\n\n📅  {event_date_full}\n📍  {event_location_full}\n\nMore details — including the full program, speakers, and ticket information — are coming soon. For now, mark your calendar.\n\nYou'll be among the first to know when registration opens.\n\n— {organizer_name}, {org_name}",
  },
  {
    id: 'reg-open',
    name: 'Registration Now Open',
    description: 'Registration launch announcement',
    channels: ['email', 'push'],
    audience: 'subscribers',
    subject: 'Registration is now open — {event_title}',
    subjects: [
      'Registration is now open — {event_title}',
      '{first_name}, your spot at {event_title} is waiting',
      'Tickets are live: {event_title} | {event_date_short}',
    ],
    body: "Hi {first_name},\n\nRegistration for {event_title} is officially open.\n\n📅  {event_date_full}\n📍  {event_location_full}\n🏷  Starting at {lowest_ticket_price}\n\n{early_bird_blurb}\n\nRegister now: {register_url}\n\n— {org_name}",
  },
  {
    id: 'early-bird',
    name: 'Early Bird Ending Soon',
    description: 'Early bird pricing deadline reminder',
    channels: ['email'],
    audience: 'subscribers',
    subject: 'Early bird pricing ends {early_bird_deadline} — {event_title}',
    subjects: [
      'Early bird pricing ends {early_bird_deadline} — {event_title}',
      'Last chance to save {early_bird_savings} on {event_title}',
      '{first_name}, your discount expires in {days_remaining} days',
    ],
    body: "Hi {first_name},\n\nJust a quick heads up — early bird pricing for {event_title} ends on {early_bird_deadline}.\n\nAfter that date, the price goes up by {price_increase_amount}.\n\n📅  {event_date_full}\n📍  {event_location_full}\n🏷  Save {early_bird_savings} — register before {early_bird_deadline}\n\nRegister now: {register_url}\n\n— {org_name}",
  },
  {
    id: 'lineup-announcement',
    name: 'Speaker / Agenda Lineup Announcement',
    description: 'Announce confirmed speakers and program highlights',
    channels: ['email'],
    audience: 'subscribers',
    subject: 'Announcing the {event_title} lineup',
    subjects: [
      'Announcing the {event_title} lineup',
      'Meet your {event_title} speakers',
      'The {event_title} program is set — here\'s what\'s coming',
    ],
    body: "Hi {first_name},\n\nWe're thrilled to announce the lineup for {event_title}.\n\n{speaker_list_block}\n\nPlus: {program_highlights}\n\n📅  {event_date_full}  ·  📍  {event_location_full}\n\nSee the full agenda and grab your spot: {register_url}\n\n— {org_name}",
  },
  {
    id: 'sold-out',
    name: 'Sold Out / Join Waitlist',
    description: 'Event sold out — waitlist invitation',
    trigger: 'auto_capacity_reached',
    channels: ['email'],
    audience: 'unregistered_subscribers',
    subject: '{event_title} is officially sold out',
    subjects: [
      '{event_title} is officially sold out',
      'We\'re sold out — but you can still get in',
      'Last update on {event_title} tickets',
    ],
    body: "Hi {first_name},\n\nWe have some exciting — and bittersweet — news.\n\n{event_title} is officially sold out.\n\nEvery ticket has been claimed, and we're beyond grateful for the response.\n\nSTILL WANT TO ATTEND?\nJoin the official waitlist. If a registered attendee cancels, you'll be notified immediately — in the order you signed up.\n\nJoin the waitlist: {waitlist_url}\n\n— {organizer_name}, {org_name}",
  },
  {
    id: 'vip-invite',
    name: 'VIP / Exclusive Invitation',
    description: 'Private invitation for VIP or select guests',
    channels: ['email'],
    audience: 'vip_list',
    subject: 'An exclusive invitation — {event_title}',
    subjects: [
      'An exclusive invitation — {event_title}',
      '{first_name}, you\'re invited to {event_title} as our guest',
      'Reserved for you: VIP access to {event_title}',
    ],
    body: "Hi {first_name},\n\nYou've been personally selected for an exclusive invitation to {event_title}.\n\n{vip_offer_details}\n\nYour VIP access includes: {vip_benefits_list}\n\nThis invitation is reserved for you until {rsvp_deadline}.\n\nAccept your invitation: {vip_rsvp_url}\n\n— {organizer_name}, {org_name}",
  },
  {
    id: 'sponsor-thanks',
    name: 'Sponsor Thank-You',
    description: 'Post-event acknowledgment to sponsors with impact summary',
    trigger: 'post_event',
    channels: ['email'],
    audience: 'sponsors',
    subject: 'Thank you for sponsoring {event_title}',
    subjects: [
      'Thank you for sponsoring {event_title}',
      '{org_name} + {sponsor_org_name} — {event_title} impact report',
      'Your {event_title} sponsorship by the numbers',
    ],
    body: "Hi {sponsor_contact_name},\n\nThank you for sponsoring {event_title}. Your support made this event possible and we want to share the results with you.\n\n{event_title} by the numbers:\n• {attendee_count} total attendees\n• {sponsor_lead_count} leads captured via your booth/presence\n• {survey_nps} average attendee NPS\n\n{custom_sponsor_message}\n\nWe'd love to discuss future partnership opportunities.\n\n— {organizer_name}, {org_name}",
  },
  {
    id: 'exhibitor-logistics',
    name: 'Exhibitor Day-Of Logistics',
    description: 'Setup instructions and day-of details for exhibitors',
    trigger: 'scheduled',
    channels: ['email'],
    audience: 'exhibitors',
    subject: 'Your exhibitor logistics for {event_title}',
    subjects: [
      'Your exhibitor logistics for {event_title}',
      '{event_title} exhibitor setup — everything you need to know',
      'Action required: exhibitor setup details for {event_title}',
    ],
    body: "Hi {exhibitor_contact_name},\n\nHere are the key logistics for your {org_name} exhibitor booth at {event_title}.\n\nSETUP\nMove-in: {move_in_time}\nBooth location: {booth_location}\nBooth size: {booth_size}\nTable/chairs: {furniture_provided}\n\nEVENT HOURS\n{event_hours_table}\n\nMOVE-OUT\n{move_out_time}\n\nOn-site contact: {onsite_contact_name} — {onsite_contact_phone}\n\nFull exhibitor guide: {exhibitor_guide_url}\n\n— {org_name}",
  },
  {
    id: 'session-reminder',
    name: 'Session Starting Soon',
    description: 'Push notification sent 10-15 minutes before a session starts',
    trigger: 'pre_session',
    channels: ['push'],
    audience: 'confirmed',
    subject: '{session_title} starts in {minutes_until_start} minutes',
    body: "{session_title} is starting soon in {session_room}. Head over now — doors open in {minutes_until_start} minutes.",
  },
  {
    id: 'cert-delivery',
    name: 'Certificate Delivery',
    description: 'Delivers the certificate PDF — fires after organizer sends or auto-schedule',
    trigger: 'certificate_issued',
    channels: ['email'],
    audience: 'confirmed',
    subject: 'Your certificate from {event_title} is ready',
    subjects: [
      'Your certificate from {event_title} is ready',
      '{first_name}, your {cert_type} is attached',
      'Download your {event_title} certificate of {cert_type_short}',
    ],
    body: "Hi {first_name},\n\nThank you for attending {event_title}. Your certificate is ready.\n\nCertificate Type: {cert_type}\nIssued To: {attendee_full_name}\nCertificate ID: {certificate_id}\n\nDownload your certificate: {cert_download_url}\nVerify online: prezva.app/verify/{certificate_id}\n\nKeep this email as your record of completion.\n\n— {organizer_name}, {org_name}",
  },
  {
    id: 'photo-share',
    name: 'Photos Are Up',
    description: 'Post-event photo gallery notification',
    trigger: 'post_event',
    channels: ['email', 'push'],
    audience: 'confirmed',
    subject: 'Photos from {event_title} are live',
    subjects: [
      'Photos from {event_title} are live',
      'Check out the {event_title} photo gallery',
      '{first_name}, the photos from {event_title} are ready',
    ],
    body: "Hi {first_name},\n\nThe photos from {event_title} are ready to view and download.\n\nView the gallery: {photo_gallery_url}\n\n{photo_share_cta}\n\nThanks again for being part of {event_title}. We hope you had a great time.\n\n— {org_name}",
  },
  {
    id: 'feedback-reminder',
    name: 'Feedback Reminder',
    description: 'Second nudge to complete the post-event survey',
    trigger: 'post_event',
    channels: ['email'],
    audience: 'confirmed_no_survey',
    subject: 'A quick favor — your feedback on {event_title}',
    subjects: [
      'A quick favor — your feedback on {event_title}',
      'Two minutes of your time — {event_title} survey',
      'Still time to share your thoughts on {event_title}',
    ],
    body: "Hi {first_name},\n\nWe noticed you haven't had a chance to complete our post-event survey yet.\n\nIt takes about 2 minutes and helps us make every future {org_name} event better. Your honest feedback matters.\n\nShare your thoughts: {survey_url}\n\nThe survey closes {survey_close_date}.\n\nThank you — we really do read every response.\n\n— {organizer_name}, {org_name}",
  },
  {
    id: 'next-event-teaser',
    name: 'Next Event / Re-engagement',
    description: 'Announce the next event and re-engage past attendees',
    trigger: 'post_event',
    channels: ['email'],
    audience: 'past_attendees',
    subject: "We're already planning the next {org_name} event",
    subjects: [
      "We're already planning the next {org_name} event",
      '{first_name}, save the date — {next_event_title}',
      'What\'s next from {org_name} — {next_event_month_year}',
    ],
    body: "Hi {first_name},\n\nThank you for attending {event_title}. We hope it was worth your time.\n\nWe're already planning our next event and wanted to give you first notice.\n\n{next_event_preview}\n\nInterested? Let us know and we'll make sure you're on the early access list.\n\nReply to this email or visit: {org_website}\n\n— {organizer_name}, {org_name}",
  },
]
