import type { AnnouncementTemplate } from './types'

export const ANNOUNCEMENT_TEMPLATES: AnnouncementTemplate[] = [
  {
    id: 'welcome',
    name: 'Welcome',
    description: 'Sent immediately after registration',
    trigger: 'on_registration',
    channels: ['email', 'push'],
    audience: 'newly_registered',
    subject: 'Welcome to {event_title}!',
    body: "Hi {attendee_name},\n\nYou're registered for {event_title} on {event_date} at {venue_name}. We're excited to see you!\n\nSave your QR code: {qr_url}\nView the agenda: {agenda_url}\nAdd to your calendar: {ics_url}\n\nQuestions? Reply to this email.\n\n— {org_name}",
  },
  {
    id: 'day-of-reminder',
    name: 'Day-of reminder',
    description: 'Sent morning of event',
    trigger: 'scheduled',
    channels: ['email', 'push'],
    audience: 'confirmed',
    subject: 'See you today at {event_title}',
    body: "Hi {attendee_name},\n\nTonight's the night (or today's the day)! {event_title} kicks off at {event_start_time} at {venue_name}.\n\nDon't forget your QR code: {qr_url}\n\nSee you soon!\n\n— {org_name}",
  },
  {
    id: 'schedule-update',
    name: 'Schedule update',
    description: 'Generic schedule change announcement',
    channels: ['email', 'push'],
    audience: 'confirmed',
    subject: 'Schedule update for {event_title}',
    body: 'Quick update — {DESCRIBE_CHANGE_HERE}.\n\nThe updated agenda is here: {agenda_url}\n\nThanks for your flexibility.\n\n— {org_name}',
  },
  {
    id: 'speaker-spotlight',
    name: 'Speaker spotlight',
    description: 'Promote a specific speaker',
    channels: ['email'],
    audience: 'confirmed',
    subject: "Don't miss {speaker_name} at {event_title}",
    body: '{speaker_name} ({speaker_role} at {speaker_company}) is speaking on "{session_title}" at {session_time}.\n\nHere\'s what to expect: {session_description}\n\nView session: {session_url}',
  },
  {
    id: 'thank-you-and-survey',
    name: 'Post-event thank-you + survey',
    description: 'Thank attendees and link to survey',
    trigger: 'post_event',
    channels: ['email'],
    audience: 'confirmed',
    subject: 'Thank you for attending {event_title}',
    body: 'Hi {attendee_name},\n\nThank you for being part of {event_title}. We hope it was valuable.\n\nWe\'d love your feedback (90 seconds): {survey_url}\n\n{certificate_download_link_if_eligible}\n\nUntil next time,\n— {org_name}',
  },
  {
    id: 'networking-nudge',
    name: 'Networking nudge',
    description: 'Encourage attendees to engage with networking features',
    channels: ['email', 'push'],
    audience: 'confirmed_pre_event',
    subject: 'Try the {event_title} networking feature',
    body: "Hi {attendee_name},\n\nWe've set up a networking directory + meetup scheduler. Get a head start on who you want to meet.\n\nOpt in here: {profile_url}",
  },
  {
    id: 'last-call',
    name: 'Last call',
    description: 'Sent 24h before registration closes',
    channels: ['email', 'push'],
    audience: 'public',
    subject: 'Last day to register for {event_title}',
    body: 'Registration for {event_title} closes tomorrow.\n\n{capacity_remaining_blurb}\n\nRegister: {event_url}',
  },
]
