import type { BadgeTemplate } from './types'

export const BADGE_TEMPLATES: BadgeTemplate[] = [
  {
    id: 'standard-qr',
    name: 'Standard with QR',
    description: 'Name, title/company, QR code in lower-right',
    layout: 'portrait',
    size: { width_mm: 89, height_mm: 102 },
    fields: [
      { type: 'text', binding: 'attendee_name', x: 5, y: 30, w: 79, h: 12, font_size: 22, weight: 'bold' },
      { type: 'text', binding: 'attendee_title', x: 5, y: 45, w: 79, h: 8, font_size: 11 },
      { type: 'text', binding: 'attendee_company', x: 5, y: 53, w: 79, h: 8, font_size: 11 },
      { type: 'qr', binding: 'qr_code', x: 60, y: 70, w: 25, h: 25 },
      { type: 'text', binding: 'event_title', x: 5, y: 5, w: 79, h: 10, font_size: 14, weight: 'bold', align: 'center' },
    ],
    accent_color_var: 'attendee_ticket_color',
  },
  {
    id: 'vip-with-photo',
    name: 'VIP with photo',
    description: 'Photo + name + role + gold accent — for VIP-tier badges',
    layout: 'portrait',
    size: { width_mm: 89, height_mm: 102 },
    fields: [
      { type: 'text', binding: 'event_title', x: 5, y: 5, w: 79, h: 10, font_size: 14, weight: 'bold', align: 'center' },
      { type: 'image', binding: 'attendee_photo_url', x: 30, y: 18, w: 30, h: 30, shape: 'circle' },
      { type: 'text', binding: 'attendee_name', x: 5, y: 52, w: 79, h: 12, font_size: 22, weight: 'bold', align: 'center' },
      { type: 'text', binding: 'attendee_title', x: 5, y: 66, w: 79, h: 8, font_size: 11, align: 'center' },
      { type: 'text', binding: 'attendee_company', x: 5, y: 74, w: 79, h: 8, font_size: 11, align: 'center' },
      { type: 'text', static: 'VIP', x: 5, y: 87, w: 79, h: 10, font_size: 16, weight: 'bold', align: 'center', color: '#D4AF37' },
      { type: 'qr', binding: 'qr_code', x: 65, y: 87, w: 20, h: 20 },
    ],
    accent_color: '#D4AF37',
  },
  {
    id: 'speaker-with-bio',
    name: 'Speaker with bio',
    description: 'Name + title + 2-line bio + Speaker accent + larger size',
    layout: 'portrait',
    size: { width_mm: 102, height_mm: 127 },
    fields: [
      { type: 'text', static: 'SPEAKER', x: 5, y: 5, w: 92, h: 10, font_size: 16, weight: 'bold', align: 'center', color: '#00BFA6' },
      { type: 'image', binding: 'speaker_photo_url', x: 36, y: 18, w: 30, h: 30, shape: 'circle' },
      { type: 'text', binding: 'speaker_name', x: 5, y: 52, w: 92, h: 12, font_size: 24, weight: 'bold', align: 'center' },
      { type: 'text', binding: 'speaker_role', x: 5, y: 66, w: 92, h: 8, font_size: 12, align: 'center' },
      { type: 'text', binding: 'speaker_company', x: 5, y: 74, w: 92, h: 8, font_size: 12, align: 'center' },
      { type: 'text', binding: 'speaker_bio_short', x: 5, y: 88, w: 92, h: 24, font_size: 10, align: 'center', wrap: true },
      { type: 'qr', binding: 'speaker_qr', x: 78, y: 110, w: 20, h: 20 },
    ],
    accent_color: '#00BFA6',
  },
  {
    id: 'volunteer',
    name: 'Volunteer',
    description: 'Volunteer badge with role designation and red accent',
    layout: 'portrait',
    size: { width_mm: 89, height_mm: 102 },
    fields: [
      { type: 'text', static: 'VOLUNTEER', x: 5, y: 5, w: 79, h: 14, font_size: 22, weight: 'bold', align: 'center', color: '#dc2626' },
      { type: 'text', binding: 'volunteer_name', x: 5, y: 40, w: 79, h: 14, font_size: 24, weight: 'bold', align: 'center' },
      { type: 'text', binding: 'volunteer_role', x: 5, y: 55, w: 79, h: 8, font_size: 12, align: 'center' },
      { type: 'text', binding: 'shift_time', x: 5, y: 65, w: 79, h: 8, font_size: 10, align: 'center', color: '#666' },
    ],
    accent_color: '#dc2626',
  },
  {
    id: 'staff-minimal',
    name: 'Staff',
    description: 'Minimal staff badge with role',
    layout: 'portrait',
    size: { width_mm: 89, height_mm: 102 },
    fields: [
      { type: 'text', static: 'STAFF', x: 5, y: 5, w: 79, h: 14, font_size: 22, weight: 'bold', align: 'center', color: '#ef4444' },
      { type: 'text', binding: 'attendee_name', x: 5, y: 40, w: 79, h: 14, font_size: 24, weight: 'bold', align: 'center' },
      { type: 'text', binding: 'attendee_role', x: 5, y: 55, w: 79, h: 8, font_size: 12, align: 'center' },
    ],
    accent_color: '#ef4444',
  },

  // ── NEW 6 — all landscape 102×76mm ───────────────────────────────────────────
  {
    id: 'exhibitor-booth',
    name: 'Exhibitor / Booth',
    description: 'Company logo dominant, individual name secondary, QR for lead retrieval',
    layout: 'landscape',
    size: { width_mm: 102, height_mm: 76 },
    color_required: true,
    zpl_supported: false,
    orientation_note: 'Landscape — clip to badge holder with company logo facing up',
    fields: [
      { type: 'text', static: 'EXHIBITOR', x: 4, y: 4, w: 30, h: 8, font_size: 10, weight: 'bold', color: '#0891b2' },
      { type: 'image', binding: 'attendee_company_logo', x: 4, y: 14, w: 30, h: 18 },
      { type: 'text', binding: 'attendee_company', x: 4, y: 34, w: 50, h: 8, font_size: 14, weight: 'bold' },
      { type: 'text', binding: 'attendee_name', x: 4, y: 44, w: 60, h: 8, font_size: 12 },
      { type: 'text', binding: 'attendee_title', x: 4, y: 53, w: 60, h: 7, font_size: 10, color: '#666' },
      { type: 'text', binding: 'event_title', x: 4, y: 62, w: 60, h: 6, font_size: 9, color: '#888' },
      { type: 'qr', binding: 'qr_code', x: 74, y: 4, w: 24, h: 24 },
    ],
    accent_color: '#0891b2',
  },
  {
    id: 'media-press',
    name: 'Media / Press',
    description: 'High-visibility red, press credential ID, QR suppressed by default',
    layout: 'landscape',
    size: { width_mm: 102, height_mm: 76 },
    color_required: true,
    zpl_supported: false,
    orientation_note: 'Landscape — red top band must be color printed',
    fields: [
      { type: 'text', static: 'PRESS', x: 0, y: 0, w: 102, h: 10, font_size: 18, weight: 'bold', align: 'center', color: '#ffffff', shape: 'rect-red' },
      { type: 'text', binding: 'attendee_name', x: 4, y: 13, w: 70, h: 12, font_size: 26, weight: 'bold' },
      { type: 'text', binding: 'media_outlet_name', x: 4, y: 27, w: 70, h: 8, font_size: 14, color: '#DC2626' },
      { type: 'text', binding: 'attendee_title', x: 4, y: 37, w: 70, h: 7, font_size: 10, color: '#666' },
      { type: 'text', binding: 'media_credential_id', x: 4, y: 60, w: 50, h: 7, font_size: 9, color: '#888' },
      { type: 'image', binding: 'org_logo', x: 80, y: 52, w: 18, h: 14 },
      { type: 'text', binding: 'access_level', x: 65, y: 28, w: 32, h: 8, font_size: 10, weight: 'bold', color: '#DC2626', align: 'center' },
    ],
    accent_color: '#DC2626',
  },
  {
    id: 'sponsor-tier',
    name: 'Sponsor Tier',
    description: 'Tier-colored banner, sponsor logo dominant, attendee name secondary',
    layout: 'landscape',
    size: { width_mm: 102, height_mm: 76 },
    color_required: true,
    zpl_supported: false,
    orientation_note: 'Landscape — tier color banner requires color print',
    fields: [
      { type: 'text', binding: 'sponsor_tier_label', x: 0, y: 0, w: 102, h: 9, font_size: 11, weight: 'bold', align: 'center', color: '#ffffff', shape: 'rect-tier' },
      { type: 'image', binding: 'sponsor_org_logo', x: 4, y: 12, w: 30, h: 16 },
      { type: 'text', binding: 'sponsor_org_name', x: 4, y: 30, w: 55, h: 10, font_size: 18, weight: 'bold' },
      { type: 'text', binding: 'attendee_name', x: 4, y: 43, w: 60, h: 8, font_size: 14, color: '#666' },
      { type: 'text', binding: 'attendee_title', x: 4, y: 53, w: 60, h: 7, font_size: 10, color: '#888' },
      { type: 'text', binding: 'event_title', x: 4, y: 62, w: 60, h: 6, font_size: 9, color: '#aaa' },
      { type: 'qr', binding: 'qr_code', x: 74, y: 46, w: 24, h: 24 },
    ],
    accent_color_var: 'sponsor_tier_color',
  },
  {
    id: 'workshop-participant',
    name: 'Workshop Participant',
    description: 'Pronouns field, table-tent format option, workshop cohort label',
    layout: 'landscape',
    size: { width_mm: 102, height_mm: 76 },
    color_required: false,
    zpl_supported: true,
    orientation_note: 'Landscape — works as table tent when folded. Thermal-compatible.',
    fields: [
      { type: 'text', binding: 'attendee_name', x: 4, y: 8, w: 70, h: 16, font_size: 28, weight: 'bold' },
      { type: 'text', binding: 'attendee_pronouns', x: 4, y: 26, w: 40, h: 7, font_size: 11, color: '#666' },
      { type: 'text', binding: 'ticket_type_name', x: 4, y: 36, w: 70, h: 7, font_size: 11, color: '#0891b2' },
      { type: 'text', binding: 'attendee_company', x: 4, y: 45, w: 70, h: 7, font_size: 10, color: '#888' },
      { type: 'text', binding: 'event_title', x: 4, y: 64, w: 60, h: 6, font_size: 9, color: '#aaa' },
      { type: 'qr', binding: 'qr_code', x: 74, y: 46, w: 24, h: 24, invert: true },
    ],
    accent_color: '#0891b2',
  },
  {
    id: 'student',
    name: 'Student',
    description: 'School, graduation year, and program — no professional fields',
    layout: 'landscape',
    size: { width_mm: 102, height_mm: 76 },
    color_required: false,
    zpl_supported: true,
    orientation_note: 'Landscape — thermal-compatible, no color required',
    fields: [
      { type: 'text', static: 'STUDENT', x: 4, y: 4, w: 30, h: 7, font_size: 10, weight: 'bold', color: '#059669' },
      { type: 'text', binding: 'attendee_name', x: 4, y: 14, w: 70, h: 14, font_size: 26, weight: 'bold' },
      { type: 'text', binding: 'student_institution', x: 4, y: 30, w: 70, h: 8, font_size: 13, color: '#059669' },
      { type: 'text', binding: 'graduation_year', x: 4, y: 40, w: 40, h: 7, font_size: 11, color: '#666' },
      { type: 'text', binding: 'attendee_pronouns', x: 4, y: 50, w: 40, h: 7, font_size: 10, color: '#888' },
      { type: 'text', binding: 'event_title', x: 4, y: 64, w: 60, h: 6, font_size: 9, color: '#aaa' },
      { type: 'qr', binding: 'qr_code', x: 74, y: 46, w: 24, h: 24 },
    ],
    accent_color: '#059669',
  },
  {
    id: 'day-pass',
    name: 'Day Pass',
    description: 'Amber left stripe, walk-in / on-demand, 5-second generation target',
    layout: 'landscape',
    size: { width_mm: 102, height_mm: 76 },
    color_required: false,
    zpl_supported: true,
    orientation_note: 'Landscape — thermal-compatible. Amber stripe prints as gray on monochrome.',
    fields: [
      { type: 'text', static: 'DAY PASS', x: 0, y: 0, w: 12, h: 76, font_size: 10, weight: 'bold', color: '#ffffff', shape: 'stripe-amber', rotation: 270 },
      { type: 'text', binding: 'attendee_name', x: 16, y: 8, w: 62, h: 14, font_size: 26, weight: 'bold' },
      { type: 'text', binding: 'ticket_type_name', x: 16, y: 24, w: 62, h: 7, font_size: 12, color: '#d97706' },
      { type: 'text', binding: 'event_title', x: 16, y: 34, w: 62, h: 7, font_size: 11 },
      { type: 'text', binding: 'attendee_company', x: 16, y: 44, w: 62, h: 7, font_size: 10, color: '#888' },
      { type: 'qr', binding: 'qr_code', x: 74, y: 46, w: 24, h: 24 },
    ],
    accent_color: '#d97706',
  },
]
