import type { EventTemplate } from './types'

export const EVENT_TEMPLATES: EventTemplate[] = [
  {
    id: 'annual-conference',
    name: 'Annual Conference (2-day)',
    description: 'Multi-track conference — keynote + tracks + networking',
    tags: ['conference', 'multi-day', 'multi-track'],
    duration_days: 2,
    capacity_default: 500,
    ticket_types: [
      { name: 'Free RSVP', type: 'free', price_cents: 0, quantity: 200, description: 'General admission, no cost' },
      { name: 'General Admission', type: 'paid', price_cents: 2500, quantity: 250, description: 'Full 2-day access including meals' },
      { name: 'VIP Pass', type: 'paid', price_cents: 7500, quantity: 50, description: 'GA plus VIP lounge, reserved seating, networking dinner' },
    ],
    sessions: [
      { day: 1, hours_offset: 0, duration: 60, type: 'keynote', title: 'Day 1 — Opening Keynote' },
      { day: 1, hours_offset: 1.5, duration: 60, type: 'talk', title: 'Track Session 1' },
      { day: 1, hours_offset: 3, duration: 60, type: 'workshop', title: 'Track Session 2' },
      { day: 1, hours_offset: 4.5, duration: 90, type: 'networking', title: 'Lunch + Networking' },
      { day: 1, hours_offset: 6, duration: 60, type: 'panel', title: 'Track Session 3' },
      { day: 2, hours_offset: 0, duration: 45, type: 'keynote', title: 'Day 2 — Opening Keynote' },
    ],
    tracks: [
      { name: 'Business Strategy', color: '#2DD4BF' },
      { name: 'Tech & Tools', color: '#3b82f6' },
    ],
    starter_announcements: ['welcome', 'day-of-reminder'],
    starter_survey: 'post-event-nps-plus-3',
    leaderboard_enabled: true,
    icebreakers_enabled: true,
  },
  {
    id: 'workshop',
    name: 'Workshop',
    description: 'Single-day intensive workshop',
    tags: ['workshop', 'single-day'],
    duration_days: 1,
    capacity_default: 50,
    ticket_types: [
      { name: 'Workshop Pass', type: 'paid', price_cents: 14900, quantity: 50, description: 'Includes materials and lunch' },
    ],
    sessions: [
      { day: 1, hours_offset: 0, duration: 30, type: 'introduction', title: 'Introductions' },
      { day: 1, hours_offset: 0.5, duration: 90, type: 'workshop', title: 'Module 1' },
      { day: 1, hours_offset: 2.5, duration: 60, type: 'workshop', title: 'Module 2' },
      { day: 1, hours_offset: 4, duration: 60, type: 'networking', title: 'Lunch' },
      { day: 1, hours_offset: 5, duration: 90, type: 'workshop', title: 'Module 3' },
      { day: 1, hours_offset: 7, duration: 30, type: 'wrap', title: 'Wrap-up & Q&A' },
    ],
  },
  {
    id: 'networking-mixer',
    name: 'Networking Mixer',
    description: 'Single-evening networking event',
    tags: ['networking', 'evening', 'casual'],
    duration_days: 1,
    capacity_default: 100,
    ticket_types: [
      { name: 'Free RSVP', type: 'free', price_cents: 0, quantity: 80 },
      { name: 'Member ticket', type: 'paid', price_cents: 1500, quantity: 100, membership_required: true },
    ],
    sessions: [
      { day: 1, hours_offset: 0, duration: 30, type: 'networking', title: 'Doors open + drinks' },
      { day: 1, hours_offset: 0.5, duration: 30, type: 'introduction', title: 'Welcome + intros' },
      { day: 1, hours_offset: 1, duration: 60, type: 'networking', title: 'Open networking' },
      { day: 1, hours_offset: 2, duration: 30, type: 'wrap', title: 'Close out' },
    ],
    icebreakers_enabled: true,
  },
  {
    id: 'trade-show',
    name: 'Trade Show',
    description: 'Exhibition-driven event with sponsors as primary draw',
    tags: ['trade-show', 'sponsors'],
    duration_days: 2,
    capacity_default: 1000,
    ticket_types: [
      { name: 'Free Visitor', type: 'free', price_cents: 0, quantity: 800 },
      { name: 'Trade Pro', type: 'paid', price_cents: 4900, quantity: 200, description: 'Includes B2B-only sessions' },
    ],
    sponsor_tiers_enabled: ['diamond', 'platinum', 'gold', 'silver', 'community'],
    passport_enabled: true,
  },
  {
    id: 'webinar-series',
    name: 'Webinar Series',
    description: 'Recurring online sessions over multiple weeks',
    tags: ['virtual', 'webinar', 'series'],
    duration_days: 1,
    capacity_default: 500,
    is_virtual: true,
    ticket_types: [
      { name: 'Free Registration', type: 'free', price_cents: 0, quantity: 500, description: 'Standard webinar access' },
      { name: 'Paid Access', type: 'paid', price_cents: 2900, quantity: 500, description: 'Includes on-demand replay' },
      { name: 'Series Pass', type: 'paid', price_cents: 9900, quantity: 500, description: 'Access to all sessions in the series' },
    ],
    sessions: [
      { day: 1, hours_offset: 0, duration: 5, type: 'introduction', title: 'Welcome + Housekeeping' },
      { day: 1, hours_offset: 0.1, duration: 5, type: 'introduction', title: 'Speaker Introduction' },
      { day: 1, hours_offset: 0.2, duration: 35, type: 'webinar', title: 'Main Presentation' },
      { day: 1, hours_offset: 0.8, duration: 15, type: 'panel', title: 'Live Q&A' },
    ],
    starter_survey: 'webinar-post',
  },

  // ── NEW 7 ─────────────────────────────────────────────────────────────────────
  {
    id: 'assoc-annual-meeting',
    name: 'Association Annual Meeting',
    description: 'Member governance, awards, committee meetings, and annual business meeting',
    tags: ['association', 'governance', 'annual', 'members'],
    duration_days: 2,
    capacity_default: 300,
    ce_credits_enabled: true,
    member_gating: true,
    ticket_types: [
      { name: 'Member Registration', type: 'paid', price_cents: 14900, quantity: 250, description: 'Full 2-day access', membership_required: true },
      { name: 'Non-Member Registration', type: 'paid', price_cents: 24900, quantity: 50, description: 'Non-member rate — includes membership consideration' },
      { name: 'Board / Committee Member', type: 'free', price_cents: 0, quantity: 50, description: 'Complimentary — board and committee members only' },
      { name: 'Sponsor Representative', type: 'free', price_cents: 0, quantity: 20, description: 'Complimentary sponsor access' },
    ],
    sessions: [
      { day: 1, hours_offset: 0, duration: 60, type: 'keynote', title: 'Opening Keynote — State of the Industry' },
      { day: 1, hours_offset: 1.5, duration: 60, type: 'panel', title: 'Committee Reports + Business Meeting' },
      { day: 1, hours_offset: 3, duration: 90, type: 'workshop', title: 'Member Workshop' },
      { day: 1, hours_offset: 5, duration: 90, type: 'networking', title: 'Welcome Reception + Awards' },
      { day: 2, hours_offset: 0, duration: 45, type: 'keynote', title: 'Day 2 Keynote' },
      { day: 2, hours_offset: 1.5, duration: 60, type: 'talk', title: 'Professional Development Session' },
      { day: 2, hours_offset: 3, duration: 60, type: 'wrap', title: 'Annual Business Meeting + Closing' },
    ],
    tracks: [
      { name: 'Governance', color: '#0D1B2A' },
      { name: 'Professional Development', color: '#2DD4BF' },
    ],
    starter_announcements: ['welcome', 'day-of-reminder', 'thank-you-and-survey'],
    starter_survey: 'annual-assoc-meeting-survey',
    leaderboard_enabled: false,
    sponsor_tiers_enabled: ['platinum', 'gold', 'silver'],
  },
  {
    id: 'awards-ceremony',
    name: 'Awards Ceremony',
    description: 'Formal awards dinner or celebration event with keynote and recognition',
    tags: ['awards', 'ceremony', 'gala', 'formal'],
    duration_days: 1,
    capacity_default: 200,
    ticket_types: [
      { name: 'Individual Ticket', type: 'paid', price_cents: 15000, quantity: 150, description: 'Single seat — dinner included' },
      { name: 'Table of 8', type: 'paid', price_cents: 100000, quantity: 20, description: 'Reserved table for 8 guests' },
      { name: 'Sponsor Table', type: 'free', price_cents: 0, quantity: 10, description: 'Complimentary sponsor table — invitation only' },
      { name: 'Nominee Complimentary', type: 'free', price_cents: 0, quantity: 30, description: 'Award nominees — complimentary attendance' },
    ],
    sessions: [
      { day: 1, hours_offset: 0, duration: 60, type: 'networking', title: 'Cocktail Reception + Arrivals' },
      { day: 1, hours_offset: 1, duration: 30, type: 'keynote', title: 'Welcome Remarks + Opening' },
      { day: 1, hours_offset: 1.5, duration: 60, type: 'networking', title: 'Dinner Service' },
      { day: 1, hours_offset: 2.5, duration: 90, type: 'keynote', title: 'Awards Ceremony' },
      { day: 1, hours_offset: 4, duration: 60, type: 'networking', title: 'Closing Reception' },
    ],
    starter_announcements: ['welcome', 'day-of-reminder'],
    starter_survey: 'post-event-nps-plus-3',
    sponsor_tiers_enabled: ['presenting', 'gold', 'silver'],
  },
  {
    id: 'fundraiser-gala',
    name: 'Fundraiser / Gala',
    description: 'Charity dinner or fundraising event with donation collection and auction',
    tags: ['fundraiser', 'gala', 'charity', 'nonprofit'],
    duration_days: 1,
    capacity_default: 250,
    fundraising_enabled: true,
    ticket_types: [
      { name: 'Individual Ticket', type: 'paid', price_cents: 20000, quantity: 200, description: 'Single seat — dinner and program included' },
      { name: 'VIP Table (10)', type: 'paid', price_cents: 150000, quantity: 20, description: 'Premium table for 10 — includes recognition' },
      { name: 'Sponsor Table', type: 'free', price_cents: 0, quantity: 10, description: 'Comped table for event sponsors' },
    ],
    sessions: [
      { day: 1, hours_offset: 0, duration: 60, type: 'networking', title: 'Cocktail Hour + Silent Auction Opens' },
      { day: 1, hours_offset: 1, duration: 30, type: 'keynote', title: 'Welcome + Mission Moment' },
      { day: 1, hours_offset: 1.5, duration: 75, type: 'networking', title: 'Dinner Service' },
      { day: 1, hours_offset: 2.75, duration: 60, type: 'keynote', title: 'Live Auction + Fund-a-Need' },
      { day: 1, hours_offset: 3.75, duration: 45, type: 'networking', title: 'Dessert + Closing' },
    ],
    starter_announcements: ['save-the-date', 'reg-open', 'welcome', 'day-of-reminder'],
    sponsor_tiers_enabled: ['presenting', 'gold', 'silver', 'bronze', 'community'],
  },
  {
    id: 'training-day',
    name: 'Training Day / Professional Development',
    description: 'Single-day professional training with CE credit tracking',
    tags: ['training', 'professional-development', 'ce-credits', 'single-day'],
    duration_days: 1,
    capacity_default: 60,
    ce_credits_enabled: true,
    ticket_types: [
      { name: 'Standard Registration', type: 'paid', price_cents: 19900, quantity: 50, description: 'Full-day training — includes materials and lunch' },
      { name: 'Member Rate', type: 'paid', price_cents: 14900, quantity: 50, description: 'Member discount rate', membership_required: true },
      { name: 'Speaker / Facilitator', type: 'free', price_cents: 0, quantity: 5, description: 'Complimentary for facilitators' },
    ],
    sessions: [
      { day: 1, hours_offset: 0, duration: 30, type: 'introduction', title: 'Welcome + Introductions' },
      { day: 1, hours_offset: 0.5, duration: 90, type: 'workshop', title: 'Module 1 — Core Concepts' },
      { day: 1, hours_offset: 2.5, duration: 90, type: 'workshop', title: 'Module 2 — Applied Skills' },
      { day: 1, hours_offset: 4, duration: 60, type: 'networking', title: 'Lunch Break' },
      { day: 1, hours_offset: 5, duration: 90, type: 'workshop', title: 'Module 3 — Practice + Application' },
      { day: 1, hours_offset: 6.5, duration: 30, type: 'wrap', title: 'Q&A + Wrap-Up' },
    ],
    starter_announcements: ['welcome', 'day-of-reminder', 'thank-you-and-survey'],
    starter_survey: 'training-event-post',
  },
  {
    id: 'community-summit',
    name: 'Community Summit',
    description: 'Multi-org civic event with roundtables, action planning, and community board',
    tags: ['community', 'civic', 'summit', 'roundtables'],
    duration_days: 1,
    capacity_default: 150,
    ticket_types: [
      { name: 'Community Attendee', type: 'free', price_cents: 0, quantity: 100, description: 'Open community access — free' },
      { name: 'Organization Representative', type: 'free', price_cents: 0, quantity: 40, description: 'For partner organization reps' },
      { name: 'Youth / Student', type: 'free', price_cents: 0, quantity: 25, description: 'Free for under-25' },
      { name: 'Sponsor Representative', type: 'free', price_cents: 0, quantity: 10, description: 'Complimentary — sponsor access' },
    ],
    sessions: [
      { day: 1, hours_offset: 0, duration: 30, type: 'networking', title: 'Doors Open + Community Board' },
      { day: 1, hours_offset: 0.5, duration: 30, type: 'keynote', title: 'Welcome + Community State of the Union' },
      { day: 1, hours_offset: 1, duration: 30, type: 'introduction', title: 'Icebreaker Activity' },
      { day: 1, hours_offset: 1.5, duration: 60, type: 'panel', title: 'Keynote Panel — Community Theme' },
      { day: 1, hours_offset: 2.75, duration: 45, type: 'workshop', title: 'Roundtable Sessions' },
      { day: 1, hours_offset: 3.5, duration: 60, type: 'networking', title: 'Lunch + Open Networking' },
      { day: 1, hours_offset: 4.5, duration: 45, type: 'workshop', title: 'Working Groups — Action Planning' },
      { day: 1, hours_offset: 5.5, duration: 30, type: 'wrap', title: 'Commitments + Closing' },
    ],
    starter_announcements: ['save-the-date', 'reg-open', 'welcome', 'day-of-reminder'],
    starter_survey: 'post-event-nps-plus-3',
    leaderboard_enabled: true,
    icebreakers_enabled: true,
    sponsor_tiers_enabled: ['community', 'supporting'],
  },
  {
    id: 'product-launch',
    name: 'Product Launch / Demo Day',
    description: 'Product reveal event with demos, media invite list, and press credentials',
    tags: ['product', 'launch', 'demo', 'media'],
    duration_days: 1,
    capacity_default: 100,
    ticket_types: [
      { name: 'General Admission', type: 'free', price_cents: 0, quantity: 75, description: 'Open invitation — RSVP required' },
      { name: 'Press / Media', type: 'free', price_cents: 0, quantity: 15, description: 'Media credential — invitation only' },
      { name: 'VIP / Partner', type: 'free', price_cents: 0, quantity: 20, description: 'VIP access — curated guest list' },
    ],
    sessions: [
      { day: 1, hours_offset: 0, duration: 30, type: 'networking', title: 'Arrivals + Pre-Show Networking' },
      { day: 1, hours_offset: 0.5, duration: 60, type: 'keynote', title: 'Product Launch Keynote' },
      { day: 1, hours_offset: 1.5, duration: 60, type: 'workshop', title: 'Live Demo Stations' },
      { day: 1, hours_offset: 2.5, duration: 30, type: 'panel', title: 'Q&A with the Team' },
      { day: 1, hours_offset: 3, duration: 60, type: 'networking', title: 'Reception + Media Interviews' },
    ],
    starter_announcements: ['save-the-date', 'welcome', 'day-of-reminder'],
    starter_survey: 'post-event-nps-plus-3',
    leaderboard_enabled: false,
  },
  {
    id: 'hybrid-conference',
    name: 'Hybrid Conference',
    description: 'In-person + virtual conference — separate ticket types and attendance experiences',
    tags: ['conference', 'hybrid', 'virtual', 'multi-track'],
    duration_days: 2,
    capacity_default: 400,
    is_hybrid: true,
    hybrid_capacity_default: 200,
    is_virtual: false,
    ticket_types: [
      { name: 'In-Person Pass', type: 'paid', price_cents: 29900, quantity: 200, description: 'Full 2-day in-person access' },
      { name: 'Virtual Pass', type: 'paid', price_cents: 9900, quantity: 500, description: 'Live stream + on-demand replay access' },
      { name: 'In-Person VIP', type: 'paid', price_cents: 79900, quantity: 25, description: 'In-person + VIP lounge + networking dinner' },
      { name: 'Speaker / Staff', type: 'free', price_cents: 0, quantity: 30, description: 'Complimentary — speakers and staff only' },
    ],
    sessions: [
      { day: 1, hours_offset: 0, duration: 60, type: 'keynote', title: 'Day 1 — Opening Keynote (Live + Streamed)' },
      { day: 1, hours_offset: 1.5, duration: 60, type: 'talk', title: 'Track Session 1' },
      { day: 1, hours_offset: 3, duration: 60, type: 'workshop', title: 'In-Person Workshop' },
      { day: 1, hours_offset: 4.5, duration: 90, type: 'networking', title: 'Lunch + Networking (In-Person)' },
      { day: 2, hours_offset: 0, duration: 45, type: 'keynote', title: 'Day 2 — Opening Keynote (Live + Streamed)' },
      { day: 2, hours_offset: 1.5, duration: 60, type: 'panel', title: 'Panel Discussion (Live + Streamed)' },
    ],
    tracks: [
      { name: 'In-Person Track', color: '#2DD4BF' },
      { name: 'Virtual Track', color: '#3b82f6' },
    ],
    starter_announcements: ['welcome', 'day-of-reminder', 'thank-you-and-survey'],
    starter_survey: 'general-conference-post',
    leaderboard_enabled: true,
    icebreakers_enabled: true,
    sponsor_tiers_enabled: ['platinum', 'gold', 'silver'],
  },
]
