import type { SurveyTemplate } from './types'

export const SURVEY_TEMPLATES: SurveyTemplate[] = [
  // ── ORIGINAL 6 ───────────────────────────────────────────────────────────────
  {
    id: 'post-event-nps-plus-3',
    name: 'Post-Event NPS+3',
    description: 'Quick post-event pulse: 1 NPS + 3 follow-up questions',
    tags: ['post-event', 'nps', 'quick'],
    duration_estimate_seconds: 90,
    questions: [
      { type: 'nps', label: 'On a scale of 0-10, how likely are you to recommend this event to a colleague?', required: true },
      { type: 'multi_choice', label: 'What did you find most valuable?',
        options: ['Sessions / content', 'Networking', 'Speakers', 'Vendor booths', 'Hands-on workshops', 'Food & venue'],
        multi: true, required: false },
      { type: 'long_text', label: 'What is one thing we should improve next year?', required: false },
      { type: 'boolean', label: 'May we contact you for a brief follow-up interview?', required: false },
    ],
  },
  {
    id: 'session-feedback',
    name: 'Session Feedback',
    description: 'Quick per-session feedback',
    tags: ['session', 'feedback', 'quick'],
    duration_estimate_seconds: 30,
    questions: [
      { type: 'rating', label: 'Rate this session', scale: 5, required: true },
      { type: 'multi_choice', label: 'Would you attend a follow-up on this topic?',
        options: ['Yes', 'Maybe', 'No'], required: false },
      { type: 'short_text', label: 'One word that describes this session', required: false },
    ],
  },
  {
    id: 'speaker-review',
    name: 'Speaker Review',
    description: 'Per-speaker feedback to share with speakers',
    tags: ['speaker', 'review'],
    duration_estimate_seconds: 60,
    questions: [
      { type: 'rating', label: 'Rate the speaker', scale: 5, required: true },
      { type: 'rating', label: 'Rate the content depth', scale: 5, required: true },
      { type: 'rating', label: 'Rate the engagement', scale: 5, required: true },
      { type: 'long_text', label: 'Any specific feedback for the speaker?', required: false },
      { type: 'boolean', label: 'Would you attend a session by this speaker again?', required: false },
    ],
  },
  {
    id: 'sponsor-pulse',
    name: 'Sponsor Pulse',
    description: 'Post-event satisfaction check from sponsors',
    tags: ['sponsor', 'post-event'],
    audience: 'sponsors',
    questions: [
      { type: 'rating', label: 'Rate your overall sponsorship experience', scale: 5, required: true },
      { type: 'number', label: 'How many qualified leads did you capture?', required: false },
      { type: 'multi_choice', label: 'Which activations worked best?',
        options: ['Booth traffic', 'Passport scans', 'Sponsored session', 'Email blast', 'Banner ads'], multi: true, required: false },
      { type: 'long_text', label: 'How can we improve sponsor value next year?', required: false },
    ],
  },
  {
    id: 'registration-intake',
    name: 'Registration Intake',
    description: 'Extra fields beyond standard name/email — dietary, accessibility, expectations',
    tags: ['registration', 'intake'],
    questions: [
      { type: 'multi_choice', label: 'Dietary restrictions',
        options: ['None', 'Vegetarian', 'Vegan', 'Gluten-free', 'Halal', 'Kosher', 'Other'], required: false },
      { type: 'short_text', label: 'Other dietary or accessibility needs', required: false },
      { type: 'multi_choice', label: 'What do you most hope to gain from attending?',
        options: ['Learn new skills', 'Network', 'Find clients/customers', 'Find vendors/partners', 'Just curious'], required: false },
      { type: 'short_text', label: 'How did you hear about us?', required: false },
    ],
  },
  {
    id: 'pre-event-prep',
    name: 'Pre-Event Prep',
    description: 'Sent 1 week before — set expectations and capture interests',
    tags: ['pre-event', 'prep'],
    questions: [
      { type: 'long_text', label: 'What questions do you most want answered at this event?', required: false },
      { type: 'multi_choice', label: 'Which sessions are you most interested in?', options: 'AUTOPOPULATE_SESSIONS', multi: true, required: false },
      { type: 'boolean', label: 'Will you attend the networking reception on Day 1?', required: false },
    ],
  },

  // ── NEW 15 ────────────────────────────────────────────────────────────────────
  {
    id: 'general-conference-post',
    name: 'General Conference Post-Event',
    description: 'Full post-conference survey — overall satisfaction, sessions, networking, logistics',
    tags: ['post-event', 'conference'],
    duration_estimate_seconds: 270,
    questions: [
      { type: 'nps', label: 'How likely are you to recommend this conference to a colleague or peer?', required: true },
      { type: 'rating', label: 'Overall, how satisfied were you with this conference?', scale: 5, required: true },
      { type: 'rating', label: 'How would you rate the quality of the sessions and content?', scale: 5, required: true },
      { type: 'rating', label: 'How would you rate the quality of networking opportunities?', scale: 5, required: true },
      { type: 'rating', label: 'How would you rate the venue and logistics?', scale: 5, required: true },
      { type: 'multi_choice', label: 'Which part of the conference did you find most valuable?',
        options: ['Keynote sessions', 'Breakout sessions', 'Workshops', 'Networking / receptions', 'Exhibit hall', 'Sponsor activities'],
        required: false },
      { type: 'long_text', label: 'What is one thing we should do differently next year?', required: false },
      { type: 'boolean', label: 'Are you likely to attend this event next year?', required: false },
      { type: 'boolean', label: 'May we use your feedback as a testimonial (anonymously)?', required: false },
    ],
  },
  {
    id: 'training-event-post',
    name: 'Training Event Post-Event',
    description: 'Learning outcomes and CE compliance reporting — 15 questions',
    tags: ['post-event', 'training', 'ce-credits'],
    duration_estimate_seconds: 270,
    questions: [
      { type: 'rating', label: 'Overall, how would you rate this training program?', scale: 5, required: true },
      { type: 'multi_choice', label: 'Compared to other professional development you have attended, this training was:',
        options: ['Much better', 'Somewhat better', 'About the same', 'Somewhat worse', 'Much worse', 'This is my first professional development event'],
        required: false },
      { type: 'rating', label: 'How effectively did this training achieve its stated learning objectives?', scale: 5, required: true },
      { type: 'multi_choice', label: 'Do you feel confident applying what you learned today in your work?',
        options: ['Yes, very confident', 'Somewhat confident', 'Not yet confident — I need more practice', 'No — the content was not applicable to my work'],
        required: true },
      { type: 'long_text', label: 'What is the most important thing you learned or will take away from this training?', required: true },
      { type: 'long_text', label: 'How do you plan to apply what you learned in the next 30 days?', required: false },
      { type: 'rating', label: 'How well did the training content match your skill level and experience?', scale: 5, required: false },
      { type: 'rating', label: "How would you rate the facilitator's knowledge and expertise?", scale: 5, required: true },
      { type: 'rating', label: "How would you rate the facilitator's teaching style and ability to engage the group?", scale: 5, required: true },
      { type: 'rating', label: 'How would you rate the quality and usefulness of the training materials?', scale: 5, required: false },
      { type: 'rating', label: 'How would you rate the pacing of the training?', scale: 5, required: false },
      { type: 'multi_choice', label: 'Which learning format was most effective for you?',
        options: ['Lecture / presentation', 'Small group discussion', 'Hands-on exercises', 'Case studies', 'Role play / simulation', 'Q&A'],
        required: false },
      { type: 'boolean', label: 'Would you recommend this training to a colleague?', required: true },
      { type: 'long_text', label: 'What topics should we cover in future training programs?', required: false },
      { type: 'long_text', label: 'Any additional feedback for the organizer or facilitator?', required: false },
    ],
  },
  {
    id: 'annual-assoc-meeting-survey',
    name: 'Annual Association Meeting',
    description: 'Member satisfaction, governance, and program feedback for annual meeting',
    tags: ['post-event', 'association', 'members'],
    duration_estimate_seconds: 240,
    questions: [
      { type: 'rating', label: 'Overall, how satisfied were you with this year\'s annual meeting?', scale: 5, required: true },
      { type: 'rating', label: 'How well did the program address the issues most important to our members?', scale: 5, required: true },
      { type: 'multi_choice', label: 'Which part of the meeting did you find most valuable?',
        options: ['General sessions', 'Committee meetings', 'Keynote address', 'Networking events', 'Awards ceremony', 'Business meeting / governance'],
        multi: true, required: false },
      { type: 'rating', label: 'How would you rate the quality of the speakers?', scale: 5, required: false },
      { type: 'rating', label: 'How well did the meeting venue meet your needs?', scale: 5, required: false },
      { type: 'long_text', label: 'What topics or issues should be addressed at next year\'s annual meeting?', required: false },
      { type: 'boolean', label: 'Do you plan to attend next year\'s annual meeting?', required: false },
      { type: 'long_text', label: 'Any suggestions for improving the annual meeting experience?', required: false },
    ],
  },
  {
    id: 'trade-show-post',
    name: 'Trade Show Post-Event',
    description: 'Visitor satisfaction, exhibitor value, and ROI feedback',
    tags: ['post-event', 'trade-show'],
    duration_estimate_seconds: 180,
    questions: [
      { type: 'rating', label: 'Overall, how satisfied were you with this trade show?', scale: 5, required: true },
      { type: 'rating', label: 'How would you rate the quality and relevance of exhibitors?', scale: 5, required: true },
      { type: 'number', label: 'Approximately how many exhibitor booths did you visit?', required: false },
      { type: 'multi_choice', label: 'What was your primary reason for attending?',
        options: ['Find new vendors or products', 'Stay current on industry trends', 'Network with peers', 'Attend education sessions', 'Meet with existing vendors', 'Company required attendance'],
        required: false },
      { type: 'rating', label: 'How would you rate the educational sessions offered at the show?', scale: 5, required: false },
      { type: 'boolean', label: 'Did you make or plan to make a purchasing decision based on what you saw at the show?', required: false },
      { type: 'boolean', label: 'Would you attend this trade show again next year?', required: true },
      { type: 'long_text', label: 'What types of exhibitors or products would you like to see at the next show?', required: false },
    ],
  },
  {
    id: 'workshop-post',
    name: 'Workshop Post-Event',
    description: 'Hands-on workshop feedback — skills, application, and satisfaction',
    tags: ['post-event', 'workshop'],
    duration_estimate_seconds: 150,
    questions: [
      { type: 'rating', label: 'Overall, how satisfied were you with this workshop?', scale: 5, required: true },
      { type: 'rating', label: 'How relevant was the content to your current work or goals?', scale: 5, required: true },
      { type: 'rating', label: 'How would you rate the hands-on exercises and activities?', scale: 5, required: true },
      { type: 'rating', label: "How would you rate the facilitator's expertise and delivery?", scale: 5, required: true },
      { type: 'multi_choice', label: 'Do you feel ready to apply what you learned?',
        options: ['Yes, immediately', 'Yes, with a little more practice', 'Not yet — I need more support', 'No — the content was not applicable'],
        required: true },
      { type: 'long_text', label: 'What was the most useful thing you took away from this workshop?', required: false },
      { type: 'boolean', label: 'Would you attend another workshop from this organizer?', required: false },
    ],
  },
  {
    id: 'webinar-post',
    name: 'Webinar Post-Event',
    description: 'Quick post-webinar feedback — content, presentation, and follow-up intent',
    tags: ['post-event', 'webinar', 'virtual', 'quick'],
    duration_estimate_seconds: 90,
    questions: [
      { type: 'rating', label: 'Overall, how would you rate this webinar?', scale: 5, required: true },
      { type: 'rating', label: 'How relevant was the content to your work?', scale: 5, required: true },
      { type: 'rating', label: "How would you rate the presenter's delivery and engagement?", scale: 5, required: false },
      { type: 'multi_choice', label: 'Will you watch the replay?',
        options: ['Yes — I missed parts', 'Yes — I want to rewatch', 'No — I got what I needed', 'I wasn\'t able to attend live'],
        required: false },
      { type: 'boolean', label: 'Would you attend another webinar from this organizer?', required: false },
      { type: 'long_text', label: 'What webinar topics would you like us to cover next?', required: false },
    ],
  },
  {
    id: 'networking-mixer-post',
    name: 'Networking Mixer Post-Event',
    description: 'Short 8-question post-mixer survey — headline KPI is meaningful connections made',
    tags: ['post-event', 'networking', 'quick'],
    duration_estimate_seconds: 120,
    questions: [
      { type: 'rating', label: 'How would you rate this event overall?', scale: 5, required: true },
      { type: 'boolean', label: 'Did you make at least one new meaningful connection tonight?', required: true },
      { type: 'rating', label: 'How would you rate the quality of the people and conversations at this event?', scale: 5, required: true },
      { type: 'rating', label: 'How well-organized and comfortable was the venue and atmosphere?', scale: 5, required: false },
      { type: 'multi_choice', label: 'How would you describe the energy of the event?',
        options: ['Too quiet — hard to connect', 'A bit subdued', 'Just right', 'Lively and fun', 'A bit overwhelming'],
        required: false },
      { type: 'boolean', label: 'Would you attend another mixer from this organizer?', required: true },
      { type: 'boolean', label: 'Would you recommend this event to a colleague?', required: false },
      { type: 'long_text', label: 'Any suggestions for making future mixers better?', required: false },
    ],
  },
  {
    id: 'educator-conference-survey',
    name: 'Educator Conference',
    description: 'Professional development satisfaction for teachers and educators',
    tags: ['post-event', 'education', 'professional-development'],
    duration_estimate_seconds: 240,
    questions: [
      { type: 'rating', label: 'Overall, how satisfied were you with this professional development event?', scale: 5, required: true },
      { type: 'rating', label: 'How directly applicable was the content to your teaching practice?', scale: 5, required: true },
      { type: 'multi_choice', label: 'Which session format was most effective for your learning?',
        options: ['Keynote presentation', 'Workshop / hands-on session', 'Panel discussion', 'Peer collaboration activity', 'Self-paced resource time'],
        required: false },
      { type: 'long_text', label: 'Describe one strategy or idea you plan to implement in your classroom within the next month.', required: true },
      { type: 'rating', label: 'How well did this event address current challenges in education?', scale: 5, required: false },
      { type: 'rating', label: 'How would you rate the quality of the presenters and facilitators?', scale: 5, required: true },
      { type: 'boolean', label: 'Would you attend future professional development events from this organizer?', required: false },
      { type: 'long_text', label: 'What topics should we prioritize for future professional development?', required: false },
    ],
  },
  {
    id: 'exhibitor-satisfaction',
    name: 'Exhibitor Satisfaction',
    description: 'Post-event ROI and experience feedback from exhibitors',
    tags: ['post-event', 'exhibitor'],
    audience: 'exhibitors',
    duration_estimate_seconds: 180,
    questions: [
      { type: 'rating', label: 'Overall, how satisfied were you with your experience as an exhibitor?', scale: 5, required: true },
      { type: 'rating', label: 'How would you rate the quality of visitor traffic to your booth?', scale: 5, required: true },
      { type: 'number', label: 'Approximately how many qualified leads did you capture at this event?', required: false },
      { type: 'multi_choice', label: 'How would you rate the ROI of exhibiting at this event?',
        options: ['Excellent — far exceeded expectations', 'Good — met expectations', 'Average — borderline worth it', 'Poor — did not meet expectations'],
        required: true },
      { type: 'rating', label: 'How would you rate the logistical support from the event organizer?', scale: 5, required: false },
      { type: 'rating', label: 'How would you rate the quality of event marketing and promotion?', scale: 5, required: false },
      { type: 'boolean', label: 'Would you exhibit at this event again next year?', required: true },
      { type: 'long_text', label: 'What could the organizer do to increase the value of exhibiting?', required: false },
    ],
  },
  {
    id: 'volunteer-debrief',
    name: 'Volunteer Debrief',
    description: 'Post-event debrief for volunteers — experience, training, and team feedback',
    tags: ['post-event', 'volunteer'],
    audience: 'volunteers',
    duration_estimate_seconds: 150,
    questions: [
      { type: 'rating', label: 'Overall, how satisfied were you with your volunteer experience?', scale: 5, required: true },
      { type: 'rating', label: 'How well-prepared did you feel for your role and responsibilities?', scale: 5, required: true },
      { type: 'rating', label: 'How would you rate the training and communication you received before the event?', scale: 5, required: false },
      { type: 'rating', label: 'How well did the event team support you during the event?', scale: 5, required: false },
      { type: 'multi_choice', label: 'What aspect of volunteering was most challenging?',
        options: ['Understanding my role', 'Communication from organizers', 'Managing attendees', 'Physical demands', 'Technical issues', 'Nothing — it went smoothly'],
        required: false },
      { type: 'boolean', label: 'Would you volunteer at a future event from this organizer?', required: true },
      { type: 'long_text', label: 'What could we do to better support volunteers at future events?', required: false },
    ],
  },
  {
    id: 'new-member-onboarding',
    name: 'New Member Onboarding',
    description: 'Onboarding experience survey for new association or community members',
    tags: ['onboarding', 'membership'],
    duration_estimate_seconds: 150,
    questions: [
      { type: 'rating', label: 'Overall, how satisfied are you with your onboarding experience so far?', scale: 5, required: true },
      { type: 'rating', label: 'How clear was the information you received about member benefits and resources?', scale: 5, required: true },
      { type: 'multi_choice', label: 'Which benefits or resources are most important to you?',
        options: ['Networking events', 'Professional development / training', 'Industry news and resources', 'Advocacy and representation', 'Member directory', 'Discounts and partner perks'],
        multi: true, required: false },
      { type: 'multi_choice', label: 'How did you hear about us?',
        options: ['Word of mouth / colleague', 'LinkedIn or social media', 'Search engine', 'Email', 'In-person event', 'Other'],
        required: false },
      { type: 'long_text', label: 'What made you decide to join?', required: false },
      { type: 'long_text', label: 'Is there anything we can help you with right now?', required: false },
    ],
  },
  {
    id: 'day-of-pulse',
    name: 'Day-Of Pulse Check',
    description: 'Mid-event push notification — 4 questions, real-time organizer dashboard',
    tags: ['live', 'quick', 'in-session'],
    duration_estimate_seconds: 45,
    questions: [
      { type: 'rating', label: 'How is the event going so far?', scale: 5, required: true },
      { type: 'multi_choice', label: 'Which part of the morning was most valuable to you?',
        options: 'AUTOPOPULATE_MORNING_SESSIONS', required: true },
      { type: 'multi_choice', label: 'What are you most looking forward to this afternoon?',
        options: 'AUTOPOPULATE_AFTERNOON_SESSIONS', required: false },
      { type: 'short_text', label: 'Anything we should know or change to make the afternoon better?', required: false },
    ],
  },
  {
    id: 'session-live-poll',
    name: 'Session Live Poll',
    description: '10 pre-built live polls for use during sessions — in-session engagement',
    tags: ['live', 'in-session', 'quick'],
    duration_estimate_seconds: 30,
    questions: [
      { type: 'multi_choice', label: 'How familiar are you with this topic?',
        options: ['Complete beginner', 'Some familiarity', 'Intermediate', 'Advanced / expert'],
        required: true },
      { type: 'boolean', label: 'Are you currently using any solution for this challenge in your organization?', required: false },
      { type: 'multi_choice', label: 'What is your biggest challenge in this area?',
        options: 'AUTOPOPULATE_POLL_OPTIONS', required: false },
      { type: 'boolean', label: 'Would you like more time on this topic?', required: false },
    ],
  },
  {
    id: 'speaker-post-session',
    name: 'Speaker Post-Session Self-Evaluation',
    description: 'Speaker self-evaluation form — completed after their session',
    tags: ['speaker', 'self-evaluation'],
    audience: 'speakers',
    duration_estimate_seconds: 120,
    questions: [
      { type: 'rating', label: 'How satisfied are you with how your session went overall?', scale: 5, required: true },
      { type: 'rating', label: 'How well did the session content land with the audience (based on their reactions)?', scale: 5, required: false },
      { type: 'multi_choice', label: 'What went well in your session?',
        options: ['Content delivery', 'Audience engagement', 'Timing / pacing', 'Technical setup', 'Q&A discussion', 'Visual aids / slides'],
        multi: true, required: false },
      { type: 'long_text', label: 'What would you do differently if you delivered this session again?', required: false },
      { type: 'boolean', label: 'Are you open to speaking at future events from this organizer?', required: false },
      { type: 'long_text', label: 'Any feedback for the event team about logistics or support?', required: false },
    ],
  },
  {
    id: 'venue-feedback',
    name: 'Venue Feedback',
    description: 'Venue-focused feedback for repeat events or site selection decisions',
    tags: ['post-event', 'venue', 'logistics'],
    duration_estimate_seconds: 120,
    questions: [
      { type: 'rating', label: 'Overall, how would you rate the venue for this event?', scale: 5, required: true },
      { type: 'rating', label: 'How would you rate the comfort and layout of the main event space?', scale: 5, required: true },
      { type: 'rating', label: 'How would you rate the accessibility and ease of getting to the venue?', scale: 5, required: false },
      { type: 'rating', label: 'How would you rate the food and beverage options?', scale: 5, required: false },
      { type: 'rating', label: 'How would you rate the Wi-Fi and technology support?', scale: 5, required: false },
      { type: 'boolean', label: 'Would you be happy to return to this venue for a future event?', required: true },
      { type: 'long_text', label: 'What could have been better about the venue or facilities?', required: false },
    ],
  },
]
