import type { TriviaQuestion } from './types'

export const TRIVIA_QUESTIONS: TriviaQuestion[] = [
  { id: 'tq-1', category: 'business', q: 'What does "EBITDA" stand for?',
    options: ['Earnings Before Interest, Taxes, Depreciation, Amortization', 'Estimated Business Income Tax Deduction Allowance', 'Earnings Beyond Initial Trading Date Amount', 'Equity-Based Investment Time-Decreasing Average'],
    correct: 0, difficulty: 'medium' },
  { id: 'tq-2', category: 'business', q: 'Which is a US SBA size standard for "small business"?',
    options: ['Under 100 employees', 'Under 500 employees', 'Under 1,000 employees', 'Depends on the industry'],
    correct: 3, difficulty: 'medium' },
  { id: 'tq-3', category: 'tech', q: 'What does "API" stand for?',
    options: ['Application Programming Interface', 'Automated Process Indicator', 'Advanced Programmable Integer', 'Asynchronous Processing Identifier'],
    correct: 0, difficulty: 'easy' },
  { id: 'tq-4', category: 'tech', q: 'What was the first SaaS product to hit $1B ARR?',
    options: ['Salesforce', 'Microsoft Office 365', 'Adobe Creative Cloud', 'Dropbox'],
    correct: 0, difficulty: 'hard' },
  { id: 'tq-5', category: 'birmingham', q: 'What is Birmingham, Alabama nicknamed?',
    options: ['The Magic City', 'The Iron City', 'The Steel Town', 'The Pittsburgh of the South'],
    correct: 0, difficulty: 'medium' },
  { id: 'tq-6', category: 'birmingham', q: "Birmingham's economy is now anchored largely in which industry?",
    options: ['Steel manufacturing', 'Healthcare and biotech', 'Aerospace', 'Energy'],
    correct: 1, difficulty: 'medium' },
  { id: 'tq-7', category: 'pop_culture', q: 'Which Birmingham native won Best Director at the 2018 Oscars?',
    options: ['Spike Lee', 'Sam Mendes', 'Jordan Peele', 'No Birmingham native won that year'],
    correct: 3, difficulty: 'hard' },
  { id: 'tq-8', category: 'marketing', q: 'What does "CAC" stand for in marketing?',
    options: ['Customer Acquisition Cost', 'Customer Average Conversion', 'Cumulative Account Count', 'Channel Audience Capacity'],
    correct: 0, difficulty: 'easy' },
  { id: 'tq-9', category: 'marketing', q: 'A "CTR" of 2% is generally considered:',
    options: ['Excellent', 'Above average', 'Average', 'Below average — depends entirely on channel'],
    correct: 3, difficulty: 'medium' },
  { id: 'tq-10', category: 'marketing', q: 'Which content format historically has the highest engagement on LinkedIn?',
    options: ['Text-only post', 'Single image', 'Carousel / multi-image', 'Native video'],
    correct: 2, difficulty: 'medium' },
]
