import type { TriviaQuestion } from './types'

export const TRIVIA_QUESTIONS: TriviaQuestion[] = [
  // business (trv-001 – trv-012)
  { id: 'trv-001', category: 'business', q: 'What does "EBITDA" stand for?',
    options: ['Earnings Before Interest, Taxes, Depreciation, Amortization', 'Estimated Business Income Tax Deduction Allowance', 'Earnings Beyond Initial Trading Date Amount', 'Equity-Based Investment Time-Decreasing Average'],
    correct: 0, difficulty: 'medium' },
  { id: 'trv-002', category: 'business', q: 'Which is a US SBA size standard for "small business"?',
    options: ['Under 100 employees', 'Under 500 employees', 'Under 1,000 employees', 'Depends on the industry'],
    correct: 3, difficulty: 'medium' },
  { id: 'trv-003', category: 'business', q: 'What does "B2B" stand for?',
    options: ['Business to Business', 'Buyer to Buyer', 'Brand to Brand', 'Back to Basics'],
    correct: 0, difficulty: 'easy' },
  { id: 'trv-004', category: 'business', q: 'Which company was the first to reach a $1 trillion market cap?',
    options: ['Amazon', 'Apple', 'Microsoft', 'Alphabet'],
    correct: 1, difficulty: 'medium' },
  { id: 'trv-005', category: 'business', q: 'What does "IPO" stand for?',
    options: ['Initial Public Offering', 'Investor Profit Outcome', 'Income Per Operation', 'Integrated Product Objective'],
    correct: 0, difficulty: 'easy' },
  { id: 'trv-006', category: 'business', q: 'In the US, what federal agency enforces antitrust law?',
    options: ['SEC', 'FTC', 'CFPB', 'FDIC'],
    correct: 1, difficulty: 'medium' },
  { id: 'trv-007', category: 'business', q: 'What is "bootstrapping" in startup terms?',
    options: ['Raising seed funding', 'Growing without external investment', 'Acquiring a competitor', 'Launching via crowdfunding'],
    correct: 1, difficulty: 'easy' },
  { id: 'trv-008', category: 'business', q: 'Which metric measures the percentage of customers who stop using a service?',
    options: ['CAC', 'NPS', 'Churn rate', 'LTV'],
    correct: 2, difficulty: 'easy' },
  { id: 'trv-009', category: 'business', q: "What does 'ARR' typically mean for SaaS companies?",
    options: ['Annual Revenue Report', 'Annual Recurring Revenue', 'Average Return Rate', 'Accrued Revenue Ratio'],
    correct: 1, difficulty: 'easy' },
  { id: 'trv-010', category: 'business', q: 'Which document outlines the terms of investment between a startup and investor?',
    options: ['Cap table', 'Term sheet', 'Operating agreement', 'Pitch deck'],
    correct: 1, difficulty: 'medium' },
  { id: 'trv-011', category: 'business', q: 'A "unicorn" startup is valued at or above:',
    options: ['$100 million', '$500 million', '$1 billion', '$10 billion'],
    correct: 2, difficulty: 'easy' },
  { id: 'trv-012', category: 'business', q: 'What was the first SaaS product to hit $1B ARR?',
    options: ['Salesforce', 'Microsoft Office 365', 'Adobe Creative Cloud', 'Dropbox'],
    correct: 0, difficulty: 'hard' },

  // tech (trv-013 – trv-023)
  { id: 'trv-013', category: 'tech', q: 'What does "API" stand for?',
    options: ['Application Programming Interface', 'Automated Process Indicator', 'Advanced Programmable Integer', 'Asynchronous Processing Identifier'],
    correct: 0, difficulty: 'easy' },
  { id: 'trv-014', category: 'tech', q: 'What does "SaaS" stand for?',
    options: ['Software as a Service', 'Scalable Application Architecture System', 'Synchronized Application Access Solution', 'Subscription Analytics and Automation Suite'],
    correct: 0, difficulty: 'easy' },
  { id: 'trv-015', category: 'tech', q: 'Which programming language was created by Guido van Rossum?',
    options: ['Ruby', 'Python', 'Go', 'Perl'],
    correct: 1, difficulty: 'easy' },
  { id: 'trv-016', category: 'tech', q: 'What does "SQL" stand for?',
    options: ['Structured Query Language', 'Standard Queue Logic', 'Sequential Query Loader', 'Scalable Queue Lookup'],
    correct: 0, difficulty: 'easy' },
  { id: 'trv-017', category: 'tech', q: 'What year was the first iPhone released?',
    options: ['2005', '2006', '2007', '2008'],
    correct: 2, difficulty: 'medium' },
  { id: 'trv-018', category: 'tech', q: 'Which company developed the React JavaScript library?',
    options: ['Google', 'Microsoft', 'Meta (Facebook)', 'Amazon'],
    correct: 2, difficulty: 'easy' },
  { id: 'trv-019', category: 'tech', q: 'What does "AI" in "generative AI" refer to?',
    options: ['Automated Interface', 'Artificial Intelligence', 'Adaptive Integration', 'Algorithmic Inference'],
    correct: 1, difficulty: 'easy' },
  { id: 'trv-020', category: 'tech', q: 'What does "HTTP" stand for?',
    options: ['HyperText Transfer Protocol', 'High Transfer Text Process', 'Hyperlink Text Transmission Protocol', 'Hosted Transfer and Tracking Protocol'],
    correct: 0, difficulty: 'easy' },
  { id: 'trv-021', category: 'tech', q: 'Which company owns GitHub?',
    options: ['Google', 'Amazon', 'Microsoft', 'Meta'],
    correct: 2, difficulty: 'medium' },
  { id: 'trv-022', category: 'tech', q: 'What is "the cloud" in computing?',
    options: ['Wireless internet', 'Remote servers accessed via internet', 'A type of operating system', 'Encrypted peer-to-peer storage'],
    correct: 1, difficulty: 'easy' },
  { id: 'trv-023', category: 'tech', q: 'Which protocol secures web traffic (the "S" in HTTPS)?',
    options: ['SSH', 'TLS/SSL', 'FTP', 'DNS'],
    correct: 1, difficulty: 'medium' },

  // marketing (trv-024 – trv-033)
  { id: 'trv-024', category: 'marketing', q: 'What does "CAC" stand for in marketing?',
    options: ['Customer Acquisition Cost', 'Customer Average Conversion', 'Cumulative Account Count', 'Channel Audience Capacity'],
    correct: 0, difficulty: 'easy' },
  { id: 'trv-025', category: 'marketing', q: 'A "CTR" of 2% is generally considered:',
    options: ['Excellent', 'Above average', 'Average', 'Below average — depends entirely on channel'],
    correct: 3, difficulty: 'medium' },
  { id: 'trv-026', category: 'marketing', q: 'Which content format historically has the highest engagement on LinkedIn?',
    options: ['Text-only post', 'Single image', 'Carousel / multi-image', 'Native video'],
    correct: 2, difficulty: 'medium' },
  { id: 'trv-027', category: 'marketing', q: 'What does "NPS" measure?',
    options: ['Net Profit Score', 'Net Promoter Score', 'New Product Sales', 'Network Performance Standard'],
    correct: 1, difficulty: 'easy' },
  { id: 'trv-028', category: 'marketing', q: 'What is "A/B testing" in digital marketing?',
    options: ['Testing two ad budgets', 'Comparing two versions of content or a page', 'Testing two audiences', 'Comparing two campaign timelines'],
    correct: 1, difficulty: 'easy' },
  { id: 'trv-029', category: 'marketing', q: 'What does "SEO" stand for?',
    options: ['Sales Engagement Optimization', 'Search Engine Optimization', 'Social Engagement Outreach', 'Sponsored Editorial Output'],
    correct: 1, difficulty: 'easy' },
  { id: 'trv-030', category: 'marketing', q: 'What is "LTV" (or "CLV") in a marketing context?',
    options: ['Long-Term Visibility', 'Lead-to-Value ratio', 'Customer Lifetime Value', 'Loyal Traffic Volume'],
    correct: 2, difficulty: 'easy' },
  { id: 'trv-031', category: 'marketing', q: 'What is "earned media"?',
    options: ['Paid advertising placements', 'Publicity gained through non-paid means like press or reviews', 'Owned website content', 'Social media ad spend'],
    correct: 1, difficulty: 'medium' },
  { id: 'trv-032', category: 'marketing', q: 'Which metric tracks what percentage of email recipients open an email?',
    options: ['CTR', 'Open rate', 'Bounce rate', 'Conversion rate'],
    correct: 1, difficulty: 'easy' },
  { id: 'trv-033', category: 'marketing', q: 'What is "retargeting" in digital advertising?',
    options: ['Re-sending email campaigns', 'Showing ads to users who already visited your site', 'Targeting a new demographic', 'Updating ad copy mid-campaign'],
    correct: 1, difficulty: 'medium' },

  // events (trv-034 – trv-043)
  { id: 'trv-034', category: 'events', q: 'What does "RFP" stand for in event planning?',
    options: ['Request for Proposal', 'Reserved Floor Plan', 'Required Fee Payment', 'Registered Food Provider'],
    correct: 0, difficulty: 'easy' },
  { id: 'trv-035', category: 'events', q: 'What is "attrition" in hotel event contracts?',
    options: ['Room wear and tear charge', 'Penalty for not filling the guaranteed room block', 'Early checkout fee', 'Service staff turnover rate'],
    correct: 1, difficulty: 'hard' },
  { id: 'trv-036', category: 'events', q: 'What does "F&B minimum" mean in a venue contract?',
    options: ['Minimum number of food items on the menu', 'Minimum spend on food and beverage required', 'Food and beverage setup fee', 'Minimum catering staff count'],
    correct: 1, difficulty: 'medium' },
  { id: 'trv-037', category: 'events', q: 'What is a "breakout session" at a conference?',
    options: ['A networking break between keynotes', 'A smaller, focused session separate from the main program', 'The session immediately after lunch', 'An emergency evacuation drill'],
    correct: 1, difficulty: 'easy' },
  { id: 'trv-038', category: 'events', q: 'What does "CE credit" stand for?',
    options: ['Convention Event credit', 'Continuing Education credit', 'Certificate of Enrollment credit', 'Corporate Engagement credit'],
    correct: 1, difficulty: 'easy' },
  { id: 'trv-039', category: 'events', q: 'What is a "badge pull" at a trade show?',
    options: ['Checking in without pre-registration', 'Capturing attendee contact info by scanning their badge', 'Removing an expired badge from the system', 'The badge pickup line at registration'],
    correct: 1, difficulty: 'medium' },
  { id: 'trv-040', category: 'events', q: 'What is the typical standard size for a US name badge?',
    options: ['3" x 4"', '3.5" x 4"', '4" x 3"', 'Varies — no standard'],
    correct: 1, difficulty: 'hard' },
  { id: 'trv-041', category: 'events', q: 'What does "run of show" (ROS) refer to in event production?',
    options: ['Shuttle schedule for attendees', 'A minute-by-minute timeline for the event day', 'Speaker presentation order', 'The venue setup walkthrough document'],
    correct: 1, difficulty: 'medium' },
  { id: 'trv-042', category: 'events', q: 'In event planning, what is "day-of logistics"?',
    options: ['Marketing on the day of the event', 'The operational execution details for event day', 'Same-day registration fees', 'Catering delivery schedule'],
    correct: 1, difficulty: 'easy' },
  { id: 'trv-043', category: 'events', q: 'What is "hybrid event" format?',
    options: ['An event with two different ticket price tiers', 'An event held simultaneously in-person and virtually', 'An event that spans two days', 'An event co-hosted by two organizations'],
    correct: 1, difficulty: 'easy' },

  // birmingham (trv-044 – trv-055) — local category
  { id: 'trv-044', category: 'birmingham', q: 'What is Birmingham, Alabama nicknamed?',
    options: ['The Magic City', 'The Iron City', 'The Steel Town', 'The Pittsburgh of the South'],
    correct: 0, difficulty: 'medium' },
  { id: 'trv-045', category: 'birmingham', q: "Birmingham's economy is now anchored largely in which industry?",
    options: ['Steel manufacturing', 'Healthcare and biotech', 'Aerospace', 'Energy'],
    correct: 1, difficulty: 'medium' },
  { id: 'trv-046', category: 'birmingham', q: 'What famous civil rights landmark is located in Birmingham?',
    options: ['Selma Bridge', '16th Street Baptist Church', 'Dexter Avenue Baptist Church', 'Rosa Parks Museum'],
    correct: 1, difficulty: 'medium' },
  { id: 'trv-047', category: 'birmingham', q: 'Vulcan Park in Birmingham features the largest cast iron statue in the world. Who is Vulcan?',
    options: ['Roman god of fire and the forge', 'Greek god of war', 'Norse god of thunder', 'Egyptian god of the sun'],
    correct: 0, difficulty: 'medium' },
  { id: 'trv-048', category: 'birmingham', q: 'Which major US university medical center is headquartered in Birmingham?',
    options: ['UAB (University of Alabama at Birmingham)', 'Vanderbilt Medical Center', 'Emory Healthcare', 'Duke University Hospital'],
    correct: 0, difficulty: 'easy' },
  { id: 'trv-049', category: 'birmingham', q: 'Which famous chef put Birmingham fine dining on the national map with his restaurant Highlands Bar and Grill?',
    options: ['Bobby Flay', 'Frank Stitt', 'Emeril Lagasse', 'Sean Brock'],
    correct: 1, difficulty: 'hard' },
  { id: 'trv-050', category: 'birmingham', q: 'Birmingham was founded in what year?',
    options: ['1863', '1871', '1880', '1892'],
    correct: 1, difficulty: 'hard' },
  { id: 'trv-051', category: 'birmingham', q: 'Which Birmingham-born artist is known for the hit "Patches"?',
    options: ['Percy Sledge', 'Clarence Carter', 'Wilson Pickett', 'Sam Cooke'],
    correct: 1, difficulty: 'hard' },
  { id: 'trv-052', category: 'birmingham', q: 'The Birmingham Civil Rights Institute is located on what famous street?',
    options: ['MLK Jr. Drive', 'Dexter Avenue', '16th Street N', 'Kelly Ingram Place'],
    correct: 2, difficulty: 'medium' },
  { id: 'trv-053', category: 'birmingham', q: 'Which professional sports team calls Birmingham home?',
    options: ['Birmingham Barons (minor league baseball)', 'Birmingham Bulls (hockey)', 'Birmingham Legion FC (soccer)', 'All of the above'],
    correct: 3, difficulty: 'easy' },
  { id: 'trv-054', category: 'birmingham', q: "Birmingham's Red Mountain is named for what resource extracted there?",
    options: ['Red clay', 'Iron ore', 'Copper', 'Sandstone'],
    correct: 1, difficulty: 'medium' },
  { id: 'trv-055', category: 'birmingham', q: 'Which annual Birmingham festival celebrates local music, food, and culture in Sloss Furnaces?',
    options: ['Sloss Music & Arts Festival', 'Magic City Classic', 'Birmingham Green Festival', 'Steel City Weekend'],
    correct: 0, difficulty: 'medium' },
]
